/**
 * Fallback lead data — mirrors the production Google Sheet so the demo works
 * identically whether Sheets is reachable or not.
 *
 * Last synced from sheet: 2026-05-21
 * inspectedProperty values use the fuzzy-matchable format that
 * leadBelongsToProperty() in DemoView resolves correctly.
 */

import type { SheetLead } from "./sheet"

export const DEMO_FALLBACK_LEADS: SheetLead[] = [

  // ── CAM KNOLL / PEAKE ────────────────────────────────────────────────────────
  // ── 3 Thirlmere Court, Berwick (open home 10 May 2026 — 25 attendees) ────────

  {
    id: "fb-001",
    name: "James Whitfield",
    phone: "0415 883 354",
    email: "vinuth.srirama@outlook.com",
    budget: 1150000,
    timeline: "2 to 4 weeks",
    persona: "Family buyer",
    notes: "Came with wife and two kids. Measured the backyard and asked about school zones twice. Very engaged. I spoke with James after the open — he seemed serious. Came prepared with questions and had clearly done his research on the street. Worth a follow-up call Monday.",
    inspectedProperty: "3 Thirlmere Court, Berwick VIC",
    lastContact: "2026-05-10",
    questions: ["School zone?", "Backyard dimensions?", "Renovation history?"],
  },
  {
    id: "fb-002",
    name: "Priya Nair",
    phone: "0415 883 354",
    email: "vinuth.srirama@outlook.com",
    budget: 890000,
    timeline: "4 to 6 weeks",
    persona: "First home buyer",
    notes: "Solo attendee, asked a lot of questions about the buying process. First open she's attended in Berwick. Priya mentioned she's been pre-approved but is still getting her head around the process. She asked about stamp duty concessions and seemed genuinely interested in the layout.",
    inspectedProperty: "3 Thirlmere Court, Berwick VIC",
    lastContact: "2026-04-28",
    questions: ["First home buyer grant?", "Stamp duty concessions?", "Settlement flexibility?"],
  },
  {
    id: "fb-003",
    name: "Michael Tran",
    phone: "0415 883 354",
    email: "vinuth.srirama@outlook.com",
    budget: 1400000,
    timeline: "1 to 2 weeks",
    persona: "Investor",
    notes: "Came alone, quiet but sharp. Asked about rental yield and comparable sales immediately. Didn't linger but asked for a follow-up call. Michael was focused on numbers — rental yield, vacancy rates and comparable sales. He wasn't browsing. He's done this before and has a clear investment thesis.",
    inspectedProperty: "3 Thirlmere Court, Berwick VIC",
    lastContact: "2026-05-10",
    questions: ["Rental yield?", "Vacancy rate in suburb?", "Comparable sales last 90 days?"],
  },
  {
    id: "fb-004",
    name: "Sandra Kowalski",
    phone: "0415 883 354",
    email: "vinuth.srirama@outlook.com",
    budget: 820000,
    timeline: "6 to 8 weeks",
    persona: "Downsizer",
    notes: "Retired couple, came together. Loved the single-level layout. Mentioned selling their Pakenham home of 28 years. Sandra and her husband are in no rush but are serious about downsizing. They loved the low-maintenance garden and asked about proximity to the medical centre.",
    inspectedProperty: "3 Thirlmere Court, Berwick VIC",
    lastContact: "2026-05-02",
    questions: ["Single-level living?", "Proximity to shops?", "Body corporate fees?"],
  },
  {
    id: "fb-005",
    name: "Aisha Mohammed",
    phone: "0415 883 354",
    email: "vinuth.srirama@outlook.com",
    budget: 760000,
    timeline: "3 months",
    persona: "First home buyer",
    notes: "Quiet attendee, came with her mother. Took lots of photos. Asked about the primary school catchment and bus routes. Aisha is early in her search but this property ticked her boxes aesthetically. Her mother was the cautious voice — worth nurturing over time rather than pushing.",
    inspectedProperty: "3 Thirlmere Court, Berwick VIC",
    lastContact: "2026-05-01",
    questions: ["School catchment?", "Bus routes nearby?", "How long on market?"],
  },
  {
    id: "fb-006",
    name: "Lachlan Forsythe",
    phone: "0415 883 354",
    email: "vinuth.srirama@outlook.com",
    budget: 1650000,
    timeline: "1 to 2 weeks",
    persona: "Upsizer",
    notes: "Confident, came with wife. Already owns in Narre Warren. Made comments suggesting he knows the area well. Asked about council overlays. Lachlan is upsizing from a smaller property nearby. He was comparing this to two other properties he inspected earlier that morning. Motivated and financially capable.",
    inspectedProperty: "3 Thirlmere Court, Berwick VIC",
    lastContact: "2026-05-08",
    questions: ["Council overlay?", "Extension potential?", "Off-street parking?"],
  },
  {
    id: "fb-007",
    name: "Grace Chen",
    phone: "0415 883 354",
    email: "vinuth.srirama@outlook.com",
    budget: 1020000,
    timeline: "4 to 6 weeks",
    persona: "Family buyer",
    notes: "Came with husband and toddler. Spent most time in the backyard and master bedroom. Friendly and engaged throughout. Grace was warm and asked detailed questions. Her husband was quieter but they were clearly aligned. They've been looking for about a month and are narrowing their list.",
    inspectedProperty: "3 Thirlmere Court, Berwick VIC",
    lastContact: "2026-05-03",
    questions: ["Backyard size?", "Storage options?", "Primary school rating?"],
  },
  {
    id: "fb-008",
    name: "Tom Nguyen",
    phone: "0415 883 354",
    email: "vinuth.srirama@outlook.com",
    budget: 850000,
    timeline: "6 months",
    persona: "Investor",
    notes: "Efficient attendee — in and out in 12 minutes. Took photos of the meter box and roof. Came alone. Tom didn't say much but was clearly assessing the bones of the property. He mentioned he has two other IPs in the area. Long horizon but worth keeping warm.",
    inspectedProperty: "3 Thirlmere Court, Berwick VIC",
    lastContact: "2026-04-26",
    questions: ["Rental appraisal?", "Age of roof?", "Hot water system age?"],
  },
  {
    id: "fb-009",
    name: "Melissa Hartley",
    phone: "0415 883 354",
    email: "vinuth.srirama@outlook.com",
    budget: 1180000,
    timeline: "2 to 4 weeks",
    persona: "Interstate relocation",
    notes: "Flew from Brisbane for the weekend. Has been searching online for two months. Came with a clipboard. Melissa is relocating for work and is serious about moving quickly. She had a list of questions prepared and took very detailed notes. Strong candidate.",
    inspectedProperty: "3 Thirlmere Court, Berwick VIC",
    lastContact: "2026-05-04",
    questions: ["Settlement flexibility?", "Nearest train station?", "Flood zone status?"],
  },
  {
    id: "fb-010",
    name: "Raj Patel",
    phone: "0415 883 354",
    email: "vinuth.srirama@outlook.com",
    budget: 1350000,
    timeline: "4 to 6 weeks",
    persona: "Developer",
    notes: "Measured rooms, checked ceiling heights, asked about easements. Came with a colleague who didn't introduce themselves. Raj didn't confirm his intention but the questions were clearly development-focused. Worth qualifying before investing too much time — could be a high-value buyer if the numbers work.",
    inspectedProperty: "3 Thirlmere Court, Berwick VIC",
    lastContact: "2026-04-30",
    questions: ["Easements?", "Subdivision potential?", "Council zoning?"],
  },
  {
    id: "fb-011",
    name: "Sophie Andreou",
    phone: "0415 883 354",
    email: "vinuth.srirama@outlook.com",
    budget: 940000,
    timeline: "2 to 4 weeks",
    persona: "Dual income couple",
    notes: "Came with fiancé, just got engaged. Excited energy. First open in Berwick — mentioned they want to be settled before the wedding. Sophie and her fiancé are highly motivated emotionally. They loved the kitchen and the street presence. Follow up with warmth rather than data.",
    inspectedProperty: "3 Thirlmere Court, Berwick VIC",
    lastContact: "2026-05-06",
    questions: ["Settlement timing?", "Renovation potential?", "Street noise?"],
  },
  {
    id: "fb-012",
    name: "Peter Drummond",
    phone: "0415 883 354",
    email: "vinuth.srirama@outlook.com",
    budget: 780000,
    timeline: "6 to 8 weeks",
    persona: "Downsizer",
    notes: "Came alone, recently widowed based on a comment he made. Methodical and quiet. Spent a long time in the garden. Peter seems to be making a significant life transition. He asked practical questions about maintenance costs. Approach with empathy — not a hard sell.",
    inspectedProperty: "3 Thirlmere Court, Berwick VIC",
    lastContact: "2026-04-29",
    questions: ["Maintenance costs?", "Garden irrigation system?", "Nearest medical centre?"],
  },
  {
    id: "fb-013",
    name: "Yuki Tanaka",
    phone: "0415 883 354",
    email: "vinuth.srirama@outlook.com",
    budget: 1090000,
    timeline: "3 months",
    persona: "Family buyer",
    notes: "Japanese-Australian family, parents and grandparent attended. Very thorough — checked every room and all storage. Yuki mentioned they are comparing five properties this weekend. They're methodical buyers — not impulsive. They'll need time but could be an A-grade prospect in 4 to 6 weeks.",
    inspectedProperty: "3 Thirlmere Court, Berwick VIC",
    lastContact: "2026-05-01",
    questions: ["Storage capacity?", "North-facing rooms?", "Proximity to Japanese grocery stores?"],
  },
  {
    id: "fb-014",
    name: "Brendan Walsh",
    phone: "0415 883 354",
    email: "vinuth.srirama@outlook.com",
    budget: 870000,
    timeline: "4 to 6 weeks",
    persona: "First home buyer",
    notes: "Young bloke, came alone. Mentioned his parents are helping with the deposit. Casual but asked surprisingly sharp questions. Brendan was more prepared than he looked. He'd done his homework on the street and asked about comparable sales. His parents are likely the real decision-makers.",
    inspectedProperty: "3 Thirlmere Court, Berwick VIC",
    lastContact: "2026-04-27",
    questions: ["Comparable sales?", "Deposit requirements?", "First home buyer scheme eligibility?"],
  },
  {
    id: "fb-015",
    name: "Natalie Srinivasan",
    phone: "0415 883 354",
    email: "vinuth.srirama@outlook.com",
    budget: 1250000,
    timeline: "1 to 2 weeks",
    persona: "Upsizer",
    notes: "Came with husband, currently in a 3-bed nearby. Said they've made two offers already this year that fell through. Very motivated. Natalie and her husband are frustrated buyers who are ready to move fast. That energy works in our favour — follow up within 24 hours with something specific.",
    inspectedProperty: "3 Thirlmere Court, Berwick VIC",
    lastContact: "2026-05-09",
    questions: ["Vendor motivation?", "Days on market?", "Negotiation flexibility?"],
  },
  {
    id: "fb-016",
    name: "Kevin Liu",
    phone: "0415 883 354",
    email: "vinuth.srirama@outlook.com",
    budget: 1500000,
    timeline: "2 to 4 weeks",
    persona: "Investor",
    notes: "Sharp and well-dressed. Asked to see the lease history and enquired about a two-lot subdivision. Came with a folder of notes. Kevin is clearly an experienced investor. He's looking at this as a medium-term hold with potential to subdivide. High value if he's qualified — worth a call.",
    inspectedProperty: "3 Thirlmere Court, Berwick VIC",
    lastContact: "2026-05-05",
    questions: ["Subdivision potential?", "Lease history?", "Rental yield projection?"],
  },
  {
    id: "fb-017",
    name: "Claire Thompson",
    phone: "0415 883 354",
    email: "vinuth.srirama@outlook.com",
    budget: 920000,
    timeline: "6 to 8 weeks",
    persona: "Family buyer",
    notes: "Mum and Dad with three kids in tow. Practical focus — laundry, storage, backyard safety. Asked about the primary school multiple times. Claire was engaged but clearly overwhelmed with three kids during the inspection. She needs time. Send her the floor plan and school info and let her come back.",
    inspectedProperty: "3 Thirlmere Court, Berwick VIC",
    lastContact: "2026-05-02",
    questions: ["School zone?", "Laundry space?", "Backyard fencing?"],
  },
  {
    id: "fb-018",
    name: "Oscar Ferreira",
    phone: "0415 883 354",
    email: "vinuth.srirama@outlook.com",
    budget: 1380000,
    timeline: "3 months",
    persona: "Interstate relocation",
    notes: "Relocating from Perth. Has a property to sell first. Came with wife and seemed to enjoy the suburb feel.",
    inspectedProperty: "3 Thirlmere Court, Berwick VIC",
    lastContact: "2026-04-28",
    questions: ["Timeline flexibility?", "Proximity to train?", "Suburb feel and community?"],
  },
  {
    id: "fb-019",
    name: "Hannah Park",
    phone: "0415 883 354",
    email: "vinuth.srirama@outlook.com",
    budget: 800000,
    timeline: "4 to 6 weeks",
    persona: "First home buyer",
    notes: "Came with a friend, asked questions in a whisper. Pre-approved and mentioned she'd been to 11 opens already. Quietly confident. Hannah is close to making a decision. Eleven opens is a long search — she knows what she wants. This property matched most of her criteria based on her questions.",
    inspectedProperty: "3 Thirlmere Court, Berwick VIC",
    lastContact: "2026-05-04",
    questions: ["Settlement flexibility?", "Building inspection process?", "How long on market?"],
  },
  {
    id: "fb-020",
    name: "Anthony Muscat",
    phone: "0415 883 354",
    email: "vinuth.srirama@outlook.com",
    budget: 1700000,
    timeline: "1 to 2 weeks",
    persona: "Developer",
    notes: "Came with an architect. Measured the frontage twice. Barely looked at the interior. Anthony is clearly evaluating the land, not the house. His architect was assessing setbacks and lot dimensions. Qualify the development angle before proceeding — this could be a fast close.",
    inspectedProperty: "3 Thirlmere Court, Berwick VIC",
    lastContact: "2026-05-07",
    questions: ["Lot dimensions?", "Frontage width?", "Council overlay and zoning?"],
  },
  {
    id: "fb-021",
    name: "Emma Johansson",
    phone: "0415 883 354",
    email: "vinuth.srirama@outlook.com",
    budget: 1050000,
    timeline: "2 to 4 weeks",
    persona: "Upsizer",
    notes: "Scandinavian-Australian, came with partner. Currently renting in Berwick. Very design-focused — commented on every finish and fitting. Emma and her partner have clear taste and a clear budget. They responded well to the kitchen and the outdoor entertaining. Send them the staging and finishes spec sheet.",
    inspectedProperty: "3 Thirlmere Court, Berwick VIC",
    lastContact: "2026-05-06",
    questions: ["Renovation done by owner or professional?", "Outdoor entertaining dimensions?", "Kitchen appliance inclusions?"],
  },
  {
    id: "fb-022",
    name: "Robert Gill",
    phone: "0415 883 354",
    email: "vinuth.srirama@outlook.com",
    budget: 850000,
    timeline: "6 months",
    persona: "Downsizer",
    notes: "Older gentleman, came alone. Very chatty — mostly about the history of the street. Probably not urgent but left his card. Robert is a long-horizon prospect — not worth heavy follow-up but worth a warm check-in around the three-month mark. He mentioned his children are pushing him to downsize.",
    inspectedProperty: "3 Thirlmere Court, Berwick VIC",
    lastContact: "2026-04-25",
    questions: ["Street history?", "Council rates?", "Any plans for the area?"],
  },
  {
    id: "fb-023",
    name: "Simone Dubois",
    phone: "0415 883 354",
    email: "vinuth.srirama@outlook.com",
    budget: 990000,
    timeline: "4 to 6 weeks",
    persona: "Family buyer",
    notes: "French-Australian couple with a baby. Focused on the nursery potential of the second bedroom and proximity to maternal health centre. Simone and her husband were warm and engaged. New parents making a big decision — they need reassurance more than pressure. Send them suburb lifestyle info.",
    inspectedProperty: "3 Thirlmere Court, Berwick VIC",
    lastContact: "2026-05-03",
    questions: ["Maternal health centre nearby?", "Nursery room size?", "Quiet street?"],
  },
  {
    id: "fb-024",
    name: "Marcus Webb",
    phone: "0415 883 354",
    email: "vinuth.srirama@outlook.com",
    budget: 1120000,
    timeline: "2 to 4 weeks",
    persona: "Dual income couple",
    notes: "Came with partner, both in finance. Analytical conversation — asked about historical price growth in the street and vacancy rates. Marcus and his partner will do their own due diligence thoroughly. They're not emotional buyers. Give them data — comparable sales and price growth — and let the numbers close.",
    inspectedProperty: "3 Thirlmere Court, Berwick VIC",
    lastContact: "2026-05-08",
    questions: ["Historical price growth?", "Vacancy rate?", "Comparable sales last 6 months?"],
  },

  // ── 48 President Road, Narre Warren South ────────────────────────────────────
  {
    id: "fb-026",
    name: "Natasha Burrows",
    phone: "0415 883 354",
    email: "vinuth.srirama@outlook.com",
    budget: 820000,
    timeline: "4 to 6 weeks",
    persona: "Family buyer",
    notes: "Came with husband and two primary-school kids. Spent most time in the backyard and alfresco. Very positive about the street and the block size. Natasha mentioned they have been outbid twice in Narre Warren South this year. They know the area well and are ready to move.",
    inspectedProperty: "48 President Road, Narre Warren South VIC",
    lastContact: "2026-04-28",
    questions: ["Primary school catchment?", "Alfresco dimensions?", "Any renovations planned?"],
  },
  {
    id: "fb-027",
    name: "Stefan Novak",
    phone: "0415 883 354",
    email: "vinuth.srirama@outlook.com",
    budget: 960000,
    timeline: "2 to 4 weeks",
    persona: "Investor",
    notes: "Came alone, European background, very sharp. Asked straight away about rental yield and recent comparable sales in the street. Has two existing IPs in Narre Warren and is looking to add a third in the same council zone. Finance pre-approved. This is a fast mover.",
    inspectedProperty: "48 President Road, Narre Warren South VIC",
    lastContact: "2026-04-28",
    questions: ["Rental yield estimate?", "Comparable sales in street?", "Vacancy rate in Narre Warren South?"],
  },
  {
    id: "fb-028",
    name: "Jenny Russell",
    phone: "0415 883 354",
    email: "vinuth.srirama@outlook.com",
    budget: 740000,
    timeline: "6 to 8 weeks",
    persona: "Downsizer",
    notes: "Came with husband Mark. Currently on 1.2 acres in Berwick — looking to sell and simplify. Loved the single-level flow and the low-maintenance garden. Mentioned they want to stay in the Casey corridor to be near their grandchildren. Not in a rush but genuinely interested.",
    inspectedProperty: "48 President Road, Narre Warren South VIC",
    lastContact: "2026-04-25",
    questions: ["Single-level layout?", "Nearest shopping centre?", "Garage storage?"],
  },
  {
    id: "fb-029",
    name: "Caleb Wong",
    phone: "0415 883 354",
    email: "vinuth.srirama@outlook.com",
    budget: 780000,
    timeline: "4 to 6 weeks",
    persona: "First home buyer",
    notes: "Young professional, came alone. Pre-approved at $800K. Mentioned his parents are co-borrowers. Confident and well-researched — had already looked up council rates and nearby schools online. Narre Warren South was his target suburb. He's close to a decision.",
    inspectedProperty: "48 President Road, Narre Warren South VIC",
    lastContact: "2026-04-27",
    questions: ["First home buyer grant eligibility?", "Stamp duty concessions?", "Settlement period?"],
  },

  // ── 5 Ascot Rise, Berwick ─────────────────────────────────────────────────────
  {
    id: "fb-030",
    name: "William Barker",
    phone: "0415 883 354",
    email: "vinuth.srirama@outlook.com",
    budget: 1280000,
    timeline: "2 to 4 weeks",
    persona: "Upsizer",
    notes: "Came with wife, currently in a 3-bed in Berwick Chase. Both immediately drawn to the outdoor kitchen and the renovation quality. William mentioned they'd been waiting for a Hamptons-style home in this pocket of Berwick for over a year. This is the one. Follow up quickly.",
    inspectedProperty: "5 Ascot Rise, Berwick VIC",
    lastContact: "2026-07-03",
    questions: ["Who did the renovation?", "Outdoor kitchen inclusions?", "Proximity to Berwick Grammar?"],
  },
  {
    id: "fb-031",
    name: "Catherine Leung",
    phone: "0415 883 354",
    email: "vinuth.srirama@outlook.com",
    budget: 1150000,
    timeline: "4 to 6 weeks",
    persona: "Dual income couple",
    notes: "Came with partner, both architects. Spent a long time in the kitchen and master suite discussing finish quality. Very discerning — asked about the stone benchtop supplier and the window brand. Catherine and her partner won't be rushed but they're clearly serious. Give them the spec sheet.",
    inspectedProperty: "5 Ascot Rise, Berwick VIC",
    lastContact: "2026-07-01",
    questions: ["Stone benchtop brand?", "Ceiling height throughout?", "Renovation permits available?"],
  },
  {
    id: "fb-032",
    name: "Thomas Abrahams",
    phone: "0415 883 354",
    email: "vinuth.srirama@outlook.com",
    budget: 1350000,
    timeline: "1 to 2 weeks",
    persona: "Investor",
    notes: "Experienced investor, came with a property manager. Focused on the land size and the quality of the renovation as a value anchor. Asked for rental appraisal and comparable sales immediately. Thomas moves fast — he mentioned he has funds sitting ready. A serious buyer.",
    inspectedProperty: "5 Ascot Rise, Berwick VIC",
    lastContact: "2026-07-02",
    questions: ["Rental appraisal on renovated home?", "Comparable sales nearby?", "Land size confirmed?"],
  },
  {
    id: "fb-033",
    name: "Sarah Maguire",
    phone: "0415 883 354",
    email: "vinuth.srirama@outlook.com",
    budget: 1020000,
    timeline: "3 months",
    persona: "Family buyer",
    notes: "Mum with two teenage kids. Very focused on the walking distance to Berwick Grammar. Mentioned she's been trying to get into this school zone for two years. The home theatre was a big hit with the kids. Sarah is a motivated buyer but budget is a stretch — she'll need time to arrange additional finance.",
    inspectedProperty: "5 Ascot Rise, Berwick VIC",
    lastContact: "2026-06-30",
    questions: ["Walking distance to Berwick Grammar?", "School zone confirmed?", "Any vendor flexibility on price?"],
  },

  // ── 3 Yemaya Place, Berwick ───────────────────────────────────────────────────
  {
    id: "fb-025",
    name: "Daniel Okonkwo",
    phone: "0415 883 354",
    email: "vinuth.srirama@outlook.com",
    budget: 975000,
    timeline: "2 to 4 weeks",
    persona: "Dual income couple",
    notes: "Came with partner, both professionals. Talked about commute times and working from home setup. Measured the second bedroom. Daniel and his partner are motivated — they've been looking for six weeks and have narrowed to this corridor. Both incomes give them strong borrowing capacity.",
    inspectedProperty: "3 Yemaya Place, Berwick VIC",
    lastContact: "2026-05-07",
    questions: ["Fibre internet?", "Commute to CBD?", "Parking for two cars?"],
  },
  {
    id: "fb-034",
    name: "Lily Stanojevic",
    phone: "0415 883 354",
    email: "vinuth.srirama@outlook.com",
    budget: 1050000,
    timeline: "4 to 6 weeks",
    persona: "Family buyer",
    notes: "Came with husband and a toddler. Really loved the open plan living and the alfresco. Mentioned they're currently in a two-bed unit in Berwick and have been looking to upsize for six months. Lily had good questions about the build quality and was well-prepared with a list.",
    inspectedProperty: "3 Yemaya Place, Berwick VIC",
    lastContact: "2026-05-05",
    questions: ["Build year?", "Alfresco area size?", "Primary school nearby?"],
  },
  {
    id: "fb-035",
    name: "Ryan Collier",
    phone: "0415 883 354",
    email: "vinuth.srirama@outlook.com",
    budget: 1120000,
    timeline: "2 to 4 weeks",
    persona: "Upsizer",
    notes: "Confident attendee, came alone but on the phone with his partner for most of the inspection. Currently owns a 3-bed in Pakenham. Ryan has been in the market for three months and has made two offers — both unsuccessful. Motivated and ready to move.",
    inspectedProperty: "3 Yemaya Place, Berwick VIC",
    lastContact: "2026-05-06",
    questions: ["Any other offers?", "Days on market?", "Vendor's reason for selling?"],
  },
  {
    id: "fb-036",
    name: "Mei-Ling Zhou",
    phone: "0415 883 354",
    email: "vinuth.srirama@outlook.com",
    budget: 1000000,
    timeline: "1 to 2 weeks",
    persona: "Investor",
    notes: "Came with her accountant. Very structured conversation — asked about depreciation schedule, rental yield and tenant profile. Mentioned she is adding to a portfolio of three properties in the SE corridor. Mei-Ling moves fast when the numbers work. Send her a rental appraisal.",
    inspectedProperty: "3 Yemaya Place, Berwick VIC",
    lastContact: "2026-05-04",
    questions: ["Rental yield?", "Depreciation schedule available?", "Typical tenant profile in street?"],
  },

  // ── 34 Hartsmere Drive, Berwick ───────────────────────────────────────────────
  {
    id: "fb-037",
    name: "Paul Andreacchio",
    phone: "0415 883 354",
    email: "vinuth.srirama@outlook.com",
    budget: 860000,
    timeline: "4 to 6 weeks",
    persona: "Family buyer",
    notes: "Came with wife and three young kids. Very positive about the Kingsmere estate feel — mentioned they have friends in the same street. Spent a long time on the decked pergola. Paul is a tradie and made comments about build quality that suggest he knows what to look for. Solid prospect.",
    inspectedProperty: "34 Hartsmere Drive, Berwick VIC",
    lastContact: "2026-02-08",
    questions: ["Council rates?", "Pergola dimensions?", "Primary school zone?"],
  },
  {
    id: "fb-038",
    name: "Cheryl Nguyen",
    phone: "0415 883 354",
    email: "vinuth.srirama@outlook.com",
    budget: 790000,
    timeline: "6 to 8 weeks",
    persona: "Downsizer",
    notes: "Came with husband Dave. Selling their Berwick home of 22 years — stepping down to something more manageable. They loved the ducted heating and cooling and the street presence. Cheryl was the decision-maker in the conversation. Not in a rush but has clear requirements. Low-maintenance is the key word.",
    inspectedProperty: "34 Hartsmere Drive, Berwick VIC",
    lastContact: "2026-02-06",
    questions: ["Body corporate fees?", "Maintenance history?", "Nearest medical centre?"],
  },
  {
    id: "fb-039",
    name: "Tyler Grosvenor",
    phone: "0415 883 354",
    email: "vinuth.srirama@outlook.com",
    budget: 720000,
    timeline: "3 months",
    persona: "First home buyer",
    notes: "Young couple, Tyler and his girlfriend. Very enthusiastic — first open home they've attended in Berwick. Pre-approved at $750K. Asked about the first home buyer grant and stamp duty. The pergola and the street were the stand-outs for them. Budget is a stretch but they're keen.",
    inspectedProperty: "34 Hartsmere Drive, Berwick VIC",
    lastContact: "2026-02-07",
    questions: ["First home buyer stamp duty concession?", "Any negotiation flexibility?", "Settlement period?"],
  },
  {
    id: "fb-040",
    name: "Vivek Anand",
    phone: "0415 883 354",
    email: "vinuth.srirama@outlook.com",
    budget: 900000,
    timeline: "2 to 4 weeks",
    persona: "Investor",
    notes: "Indian-Australian, came alone. Efficient inspection — checked the meter box, asked about the hot water system age, and photographed the roof. Very focused on yield and the Kingsmere estate's rental demand. Vivek has a clear investment framework and this property fits it. Worth a follow-up call.",
    inspectedProperty: "34 Hartsmere Drive, Berwick VIC",
    lastContact: "2026-02-05",
    questions: ["Rental yield estimate?", "Hot water system age?", "Vacancy rate in Berwick?"],
  },

  // ── PAS SUNILCHANDRA / AREA SPECIALIST ───────────────────────────────────────
  // ── 58 Broadway Street, Berwick ──────────────────────────────────────────────
  {
    id: "pas-001",
    name: "Liam O'Brien",
    phone: "0412 881 247",
    email: "liam.obrien.melb@gmail.com",
    budget: 980000,
    timeline: "2 to 4 months",
    persona: "Family buyer",
    notes: "Came with wife and two primary-school-aged kids. Spent time measuring the backyard. Very interested in the Kambrya College zone. Mentioned they're selling their Narre Warren apartment.",
    inspectedProperty: "58 Broadway Street, Berwick VIC",
    lastContact: "2026-05-14",
    questions: ["School zone?", "Backyard size?", "How far to Berwick train station?"],
  },
  {
    id: "pas-002",
    name: "Raj Patel",
    phone: "0432 556 178",
    email: "raj.patel.inv@gmail.com",
    budget: 1200000,
    timeline: "1 to 3 months",
    persona: "Investor",
    notes: "Came alone, methodical. Asked about rental yield immediately and wanted comparable sales data. Has 2 IPs in Casey already. Finance is approved — serious buyer.",
    inspectedProperty: "58 Broadway Street, Berwick VIC",
    lastContact: "2026-05-14",
    questions: ["Rental yield?", "Vacancy rate in Berwick?", "Comparable sales last 90 days?"],
  },
  {
    id: "pas-003",
    name: "Sophie Nguyen",
    phone: "0447 229 034",
    email: "sophie.nguyen.au@gmail.com",
    budget: 890000,
    timeline: "3 to 6 months",
    persona: "Upsizer",
    notes: "Currently renting in Berwick, looking to upsize from a 2-bed unit. Very focused on school zone and commute to Dandenong. Partner works from home so also asked about NBN.",
    inspectedProperty: "58 Broadway Street, Berwick VIC",
    lastContact: "2026-05-14",
    questions: ["School zone?", "NBN type?", "Ducted air conditioning?"],
  },

  // ── 32 Seattle Crescent, Cranbourne North ────────────────────────────────────
  {
    id: "pas-004",
    name: "David Kim",
    phone: "0408 334 952",
    email: "davidkim.re@gmail.com",
    budget: 870000,
    timeline: "2 to 5 months",
    persona: "Investor",
    notes: "Korean-Australian, very sharp. Focused on yield and vacancy rate. Took notes throughout. Mentioned he's looking at three suburbs — Cranbourne North, Clyde North, and Officer.",
    inspectedProperty: "32 Seattle Crescent, Cranbourne North VIC",
    lastContact: "2026-04-28",
    questions: ["Rental yield?", "Vacancy rate in suburb?", "Body corporate fees?"],
  },
  {
    id: "pas-005",
    name: "Priya Sharma",
    phone: "0423 445 890",
    email: "priya.sharma.fam@gmail.com",
    budget: 820000,
    timeline: "3 to 6 months",
    persona: "Family buyer",
    notes: "Came with husband and young child. Very focused on Cranbourne North Primary — mentioned their daughter is starting prep next year. Asked about the community feel and local parks.",
    inspectedProperty: "32 Seattle Crescent, Cranbourne North VIC",
    lastContact: "2026-04-28",
    questions: ["Primary school catchment?", "Quiet street?", "Parks nearby?"],
  },
  {
    id: "pas-006",
    name: "Jake Thompson",
    phone: "0456 778 012",
    email: "jake.thompson.au@hotmail.com",
    budget: 750000,
    timeline: "4 to 8 months",
    persona: "First home buyer",
    notes: "Young couple, first inspection in this suburb. Enthusiastic — asked about the first home buyer grant and stamp duty concessions. Pre-approval at $800K.",
    inspectedProperty: "32 Seattle Crescent, Cranbourne North VIC",
    lastContact: "2026-04-28",
    questions: ["First home buyer stamp duty?", "Comparable sales nearby?", "Solar system size?"],
  },

  // ── 20 Elwick Drive, Clyde North ─────────────────────────────────────────────
  {
    id: "pas-007",
    name: "Marcus Chen",
    phone: "0411 667 890",
    email: "marcus.chen.au@gmail.com",
    budget: 700000,
    timeline: "1 to 3 months",
    persona: "Investor",
    notes: "Chinese-Australian, came alone. Very direct — asked about yield, comparable sales, and vacancy rate straight away. Has SMSF. Focused on Clyde North and Officer as growth areas.",
    inspectedProperty: "20 Elwick Drive, Clyde North VIC",
    lastContact: "2026-04-05",
    questions: ["Rental yield?", "Comparable sales last 90 days?", "Vacancy rate in Clyde North?"],
  },
  {
    id: "pas-008",
    name: "Anika Johansson",
    phone: "0434 112 567",
    email: "anika.j.melb@gmail.com",
    budget: 680000,
    timeline: "2 to 4 months",
    persona: "First home buyer",
    notes: "Swedish-Australian, came with partner. First home — asked about the FHBG and stamp duty. Mentioned they want to start a family soon so school zone was important.",
    inspectedProperty: "20 Elwick Drive, Clyde North VIC",
    lastContact: "2026-04-05",
    questions: ["First home buyer grant?", "School zone?", "Future infrastructure nearby?"],
  },
]
