/**
 * Fallback lead data for offline / Sheets-timeout scenarios.
 * Mirrors the production Sheets dataset so the demo works identically
 * whether Sheets is reachable or not.
 *
 * inspectedProperty values use the fuzzy-matchable format that
 * leadBelongsToProperty() in DemoView resolves correctly.
 */

import type { SheetLead } from "./sheet"

export const DEMO_FALLBACK_LEADS: SheetLead[] = [
  // ── 3 Thirlmere Court, Berwick ─────────────────────────────────────────────
  {
    id: "fb-001",
    name: "James Whitfield",
    phone: "0412 334 891",
    email: "james.whitfield@gmail.com",
    budget: 1150000,
    timeline: "3 to 6 months",
    persona: "Family buyer",
    notes: "Came with wife and two kids. Measured the backyard and asked about school zones twice. Very engaged. I spoke with James for nearly 20 minutes — he mentioned they want to be settled before the school year.",
    inspectedProperty: "3 Thirlmere Court, Berwick VIC",
    lastContact: "2026-05-02",
    questions: ["School zone?", "Backyard dimensions?", "Renovation history?"],
  },
  {
    id: "fb-002",
    name: "Claire Thompson",
    phone: "0423 556 781",
    email: "claire.thompson@hotmail.com",
    budget: 920000,
    timeline: "2 to 4 months",
    persona: "Family buyer",
    notes: "Came with partner and young child. Focused on the second bedroom size and primary school catchment. Mentioned they're renting nearby and keen to buy before the next school enrolment period.",
    inspectedProperty: "3 Thirlmere Court, Berwick VIC",
    lastContact: "2026-05-02",
    questions: ["Primary school catchment?", "Second bedroom size?", "Walk to train?"],
  },
  {
    id: "fb-003",
    name: "Michael Tran",
    phone: "0401 228 559",
    email: "m.tran@yahoo.com.au",
    budget: 1400000,
    timeline: "1 to 3 months",
    persona: "Investor",
    notes: "Came alone, quiet but sharp. Asked about rental yield and comparable sales immediately. Didn't linger but asked for a follow-up call. Has 3 other IPs in the area.",
    inspectedProperty: "3 Thirlmere Court, Berwick VIC",
    lastContact: "2026-05-02",
    questions: ["Rental yield?", "Vacancy rate in suburb?", "Comparable sales last 90 days?"],
  },
  {
    id: "fb-004",
    name: "Kevin Liu",
    phone: "0488 774 320",
    email: "kevin.liu.inv@gmail.com",
    budget: 1500000,
    timeline: "1 to 2 months",
    persona: "Investor",
    notes: "Very methodical. Spent time in every room with a notepad. Asked about rental appraisal, body corporate, and current vacancy rate in the suburb. Has finance approved.",
    inspectedProperty: "3 Thirlmere Court, Berwick VIC",
    lastContact: "2026-05-02",
    questions: ["Rental appraisal?", "Gross yield at asking price?", "Body corporate fees?"],
  },
  {
    id: "fb-005",
    name: "Simone Dubois",
    phone: "0434 778 001",
    email: "simone.dubois@gmail.com",
    budget: 990000,
    timeline: "3 to 5 months",
    persona: "Family buyer",
    notes: "French-Australian couple with a baby. Focused on the nursery potential of the second bedroom and proximity to maternal health centre. Loved the court position.",
    inspectedProperty: "3 Thirlmere Court, Berwick VIC",
    lastContact: "2026-05-02",
    questions: ["Maternal health centre nearby?", "Nursery room size?", "Quiet street?"],
  },
  {
    id: "fb-006",
    name: "Emma Johansson",
    phone: "0423 112 990",
    email: "emma.j.melb@gmail.com",
    budget: 1050000,
    timeline: "2 to 4 months",
    persona: "Upsizer",
    notes: "Scandinavian-Australian, came with partner. Currently renting in Berwick. Very design-focused — commented on every finish. Asked about who did the renovation.",
    inspectedProperty: "3 Thirlmere Court, Berwick VIC",
    lastContact: "2026-05-02",
    questions: ["Renovation done by owner or professional?", "Outdoor entertaining dimensions?", "Kitchen appliance inclusions?"],
  },
  {
    id: "fb-007",
    name: "Sandra Kowalski",
    phone: "0438 112 974",
    email: "sandra.kowalski@gmail.com",
    budget: 820000,
    timeline: "4 to 8 months",
    persona: "Downsizer",
    notes: "Retired couple, came together. Loved the single-level layout. Mentioned selling their Pakenham home of 28 years. Sandra did most of the talking — very thorough.",
    inspectedProperty: "3 Thirlmere Court, Berwick VIC",
    lastContact: "2026-05-02",
    questions: ["Single-level living?", "Proximity to shops?", "Body corporate fees?"],
  },
  {
    id: "fb-008",
    name: "Lachlan Forsythe",
    phone: "0499 001 234",
    email: "lachlan.forsythe@gmail.com",
    budget: 1650000,
    timeline: "6 to 12 months",
    persona: "Upsizer",
    notes: "Confident, came with wife. Already owns in Narre Warren. Made comments suggesting he knows the area well and is looking to upsize for a growing family. Mentioned council overlay.",
    inspectedProperty: "3 Thirlmere Court, Berwick VIC",
    lastContact: "2026-05-02",
    questions: ["Council overlay?", "Extension potential?", "Off-street parking?"],
  },
  {
    id: "fb-009",
    name: "Aisha Mohammed",
    phone: "0411 345 678",
    email: "aisha.m@gmail.com",
    budget: 760000,
    timeline: "3 to 6 months",
    persona: "First home buyer",
    notes: "Quiet attendee, came with her mother. Took lots of photos. Asked about the primary school catchment and bus routes. Aisha mentioned this is her third open home in Berwick.",
    inspectedProperty: "3 Thirlmere Court, Berwick VIC",
    lastContact: "2026-05-02",
    questions: ["School catchment?", "Bus routes nearby?", "How long on market?"],
  },
  {
    id: "fb-010",
    name: "Anthony Muscat",
    phone: "0456 334 002",
    email: "anthony.muscat@bigpond.com",
    budget: 1700000,
    timeline: "3 to 6 months",
    persona: "Developer",
    notes: "Came with an architect. Measured the frontage twice. Barely looked at the interior. Anthony is clearly evaluating the land for potential subdivision or dual-occ.",
    inspectedProperty: "3 Thirlmere Court, Berwick VIC",
    lastContact: "2026-05-02",
    questions: ["Lot dimensions?", "Frontage width?", "Council overlay and zoning?"],
  },
  {
    id: "fb-011",
    name: "Robert Gill",
    phone: "0418 009 445",
    email: "rob.gill.aus@gmail.com",
    budget: 850000,
    timeline: "6 to 12 months",
    persona: "Downsizer",
    notes: "Older gentleman, came alone. Very chatty — mostly about the history of the street. Probably not urgent but left his card. Worth a check-in every few months.",
    inspectedProperty: "3 Thirlmere Court, Berwick VIC",
    lastContact: "2026-05-02",
    questions: ["Street history?", "Council rates?", "Any plans for the area?"],
  },
  {
    id: "fb-012",
    name: "Marcus Webb",
    phone: "0412 556 334",
    email: "marcus.webb.au@outlook.com",
    budget: 1120000,
    timeline: "3 to 6 months",
    persona: "Dual income couple",
    notes: "Came with partner, both in finance. Analytical conversation — asked about historical price growth in the street and vacancy rate. Seemed serious, taking a data-driven approach.",
    inspectedProperty: "3 Thirlmere Court, Berwick VIC",
    lastContact: "2026-05-02",
    questions: ["Historical price growth?", "Vacancy rate?", "Comparable sales last 6 months?"],
  },
  {
    id: "fb-013",
    name: "Brendan Walsh",
    phone: "0403 882 115",
    email: "brendan.walsh@me.com",
    budget: 1100000,
    timeline: "2 to 5 months",
    persona: "Family buyer",
    notes: "Easygoing, came with wife. Kids at Berwick Primary. Very focused on the school zone and the backyard. Seems to know what he wants — already sold his apartment.",
    inspectedProperty: "3 Thirlmere Court, Berwick VIC",
    lastContact: "2026-05-02",
    questions: ["School zone catchment?", "Backyard size?", "Settlement timeline?"],
  },

  // ── 3 Yemaya Place, Berwick ────────────────────────────────────────────────
  {
    id: "fb-014",
    name: "Tom Nguyen",
    phone: "0431 209 887",
    email: "tom.nguyen.au@gmail.com",
    budget: 780000,
    timeline: "4 to 8 months",
    persona: "First home buyer",
    notes: "Young couple, first inspection together. Enthusiastic — asked about the first home buyer grant and stamp duty. Have pre-approval for $800K.",
    inspectedProperty: "3 Yemaya Place, Berwick VIC",
    lastContact: "2026-03-15",
    questions: ["First home buyer grant?", "Stamp duty concessions?", "Settlement flexibility?"],
  },
  {
    id: "fb-015",
    name: "Yuki Tanaka",
    phone: "0477 334 008",
    email: "yuki.tanaka.melb@gmail.com",
    budget: 950000,
    timeline: "2 to 4 months",
    persona: "Investor",
    notes: "Japanese-Australian, very measured. Took detailed notes on the rental appraisal figure. Mentioned she owns one other property in Dandenong. Keen on school-zone suburbs.",
    inspectedProperty: "3 Yemaya Place, Berwick VIC",
    lastContact: "2026-03-15",
    questions: ["Rental appraisal?", "Vacancy rate?", "School zone for tenants?"],
  },
]
