[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "node_modules/.bin/tsx index.ts"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
