/**
 * PropOS → Supabase Migration
 * Upserts ALL past buyers from Google Sheets into Supabase.
 * Run: node scripts/supabase-migrate.mjs
 */
import { createClient } from '@supabase/supabase-js'

// Set these via env: SUPABASE_URL and SUPABASE_SERVICE_KEY
// e.g. SUPABASE_URL=https://xxx.supabase.co SUPABASE_SERVICE_KEY=<service_role_key> node scripts/supabase-migrate.mjs
const SUPABASE_URL     = process.env.SUPABASE_URL     ?? 'https://pzdcwulzteofvatjrtlh.supabase.co'
const SUPABASE_SERVICE = process.env.SUPABASE_SERVICE_KEY ?? ''
if (!SUPABASE_SERVICE) { console.error('Set SUPABASE_SERVICE_KEY env var'); process.exit(1) }

const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE, {
  auth: { autoRefreshToken: false, persistSession: false },
})

// ── All rows from Google Sheet (Past Buyers tab, 113 rows) ───────────────────
const ALL_BUYERS = [
  // ── Cameron Knoll / Peake (88 rows) ──────────────────────────────────────
  {id:5001,agent_name:"Cameron Knoll",name:"David & Karen Hollis",phone:"0418 234 567",email:"k.hollis@gmail.com",purchase_address:"31 Avondale Street",suburb:"Officer",purchase_date:"2017-03-15",purchase_price:620000,deposit:124000,property_type:"House",beds:4,baths:3,land:650,status:"owner-occupier",notes:"Lovely family. Two kids at Berwick Primary — Ella (yr 5) and Oscar (yr 3). Karen volunteers at the school canteen. David works in the city, catches the 6:42am train. They love the court position and the park across from Thirlmere. Karen mentioned wanting a bigger kitchen when they had everyone over at Christmas.",last_contact_date:"2024-11-20",personalisation_hook:"Karen mentioned wanting a bigger kitchen when they had everyone over at Christmas. 7 years on, Ella and Oscar are outgrowing Avondale Street."},
  {id:5002,agent_name:"Cameron Knoll",name:"Michael Chen",phone:"0411 567 890",email:"m.chen.property@outlook.com",purchase_address:"1 Battalion Road",suburb:"Berwick",purchase_date:"2015-08-22",purchase_price:545000,deposit:109000,property_type:"House",beds:4,baths:3,land:490,status:"owner-occupier",notes:"Michael and Fiona. Both kids have moved out — daughter in Fitzroy, son in Brisbane. House feels too big now. Michael semi-retired from engineering, Fiona still works part-time as a physio. He mentioned he'd love to be closer to the coast. Very analytical, will want to see numbers before deciding.",last_contact_date:"2026-06-02"},
  {id:5003,agent_name:"Cameron Knoll",name:"Sandra Moore",phone:"0422 891 234",email:"sandra.moore2@gmail.com",purchase_address:"3 Pembroke Court",suburb:"Berwick",purchase_date:"2020-02-10",purchase_price:710000,deposit:71000,property_type:"House",beds:3,baths:2,land:430,status:"owner-occupier",notes:"Single mum, absolute trooper. Has two boys (7 and 5) and third baby due August 2026. Current 3-bed is getting very tight. She mentioned wanting a study nook for working from home. Very budget-conscious but knows she needs more space. School zone is important — wants to stay in Berwick Chase catchment.",last_contact_date:"2025-03-01"},
  {id:5004,agent_name:"Cameron Knoll",name:"James & Lisa Thompson",phone:"0404 123 456",email:"jlthompson@hotmail.com",purchase_address:"11 Coachella Way",suburb:"Berwick",purchase_date:"2018-11-30",purchase_price:785000,deposit:157000,property_type:"House",beds:3,baths:2,land:560,status:"owner-occupier",notes:"James is a plumber, Lisa is a nurse at Casey Hospital. Both kids have finished uni and moved out. Lisa mentioned at the last catch-up that the garden is too much work now. They've been talking about a townhouse in Narre Warren South — less maintenance, closer to the shops. Lisa is the decision maker.",last_contact_date:"2024-06-01"},
  {id:5005,agent_name:"Cameron Knoll",name:"Robert Patel",phone:"0431 678 901",email:"rob.patel@gmail.com",purchase_address:"55 Armitage Drive",suburb:"Narre Warren South",purchase_date:"2019-05-14",purchase_price:680000,deposit:136000,property_type:"House",beds:5,baths:2,land:890,status:"investor",notes:"Investment property — Rob lives in South Yarra. Currently tenanted at $520/wk. Tenant lease expires November 2026. Rob mentioned he's thinking about selling one of his three IPs to free up capital for a commercial investment in Dandenong. Very numbers-driven, responds to yield and tax analysis.",last_contact_date:"2025-01-15"},
  {id:5006,agent_name:"Cameron Knoll",name:"Sarah & Tom Mitchell",phone:"0413 445 678",email:"smitchell.family@gmail.com",purchase_address:"29 Charleston Chase",suburb:"Berwick",purchase_date:"2016-06-20",purchase_price:695000,deposit:139000,property_type:"House",beds:4,baths:2,land:560,status:"owner-occupier",notes:"Sarah and Tom have three kids — oldest just started Year 7. Tom works at Bunnings head office, Sarah is a school teacher. They absolutely love the street and the neighbours. Tom mentioned at the last open home catch-up that they've been thinking about a pool. Might be a renovate vs sell decision for them.",last_contact_date:"2024-08-14"},
  {id:5007,agent_name:"Cameron Knoll",name:"Wei & Helen Zhang",phone:"0408 990 112",email:"weizhang.invest@outlook.com",purchase_address:"74 Wurundjeri Boulevard",suburb:"Berwick",purchase_date:"2014-11-08",purchase_price:580000,deposit:116000,property_type:"House",beds:4,baths:2,land:620,status:"investor",notes:"Wei and Helen own two IPs in the Berwick corridor. This one is rented at $540/wk on a 12-month lease. Helen called last month asking about current values — she said they want to consolidate their portfolio into one better property closer to the CBD. Very investment-minded, will move quickly if the numbers make sense.",last_contact_date:"2025-03-22"},
  {id:5008,agent_name:"Cameron Knoll",name:"Paul Donovan",phone:"0499 334 112",email:"pdonovan55@yahoo.com.au",purchase_address:"19 Embling Street",suburb:"Berwick",purchase_date:"2019-09-05",purchase_price:650000,deposit:65000,property_type:"House",beds:3,baths:2,land:520,status:"owner-occupier",notes:"Paul is a single dad — his two teenagers are almost done with school and looking at uni in the city. He works remotely for a logistics company. Mentioned he feels a bit isolated out in Officer and would prefer somewhere closer to family in Cranbourne. Good equity position, realistic about the market.",last_contact_date:"2024-09-30"},
  {id:5009,agent_name:"Cameron Knoll",name:"Anthony Nguyen",phone:"0455 334 667",email:"a.nguyen.prop@gmail.com",purchase_address:"23 Coachella Way",suburb:"Berwick",purchase_date:"2017-07-14",purchase_price:485000,deposit:48500,property_type:"House",beds:4,baths:2,land:580,status:"investor",notes:"Anthony is a builder living in Seaford. This was his first IP — bought it with a 10% deposit when he was 24. It's been rented solidly for 7 years. He mentioned he wants to use the equity to build a spec home in Clyde North. Younger investor, comfortable with risk, just needs to see the equity number to pull the trigger.",last_contact_date:"2024-07-30"},
  {id:5010,agent_name:"Cameron Knoll",name:"Emma & Josh Wilson",phone:"0406 789 012",email:"emma.wilson.home@gmail.com",purchase_address:"11 Buchanan Road",suburb:"Berwick",purchase_date:"2018-04-18",purchase_price:785000,deposit:157000,property_type:"House",beds:3,baths:1,land:490,status:"owner-occupier",notes:"Emma and Josh are a high-energy couple — Josh runs a gym, Emma is a dental hygienist. They've renovated the kitchen and master suite beautifully. Third kid on the way and they're already looking at properties in Pakenham Upper or Gembrook for some land. Said they'd probably sell mid-2026 when Emma is back at work.",last_contact_date:"2025-01-08"},
  {id:5011,agent_name:"Cameron Knoll",name:"Frank & Maria Russo",phone:"0417 223 445",email:"russo.frank@bigpond.com",purchase_address:"3 Camelot Court, Berwick",suburb:"Berwick",purchase_date:"2013-07-10",purchase_price:455000,deposit:91000,property_type:"House",beds:4,baths:2,land:672,status:"owner-occupier",notes:"Frank and Maria are both in their late 60s and ready to downsize. Frank retired from the council last year. Maria has had some health issues and wants something single-level, smaller garden, closer to the Berwick Village. Both their kids are in Berwick so staying in the suburb is non-negotiable. Very motivated.",last_contact_date:"2024-10-05"},
  {id:5012,agent_name:"Cameron Knoll",name:"Derek & Shannon O'Brien",phone:"0421 667 889",email:"shannobrien@gmail.com",purchase_address:"27 Springvale Road, Officer",suburb:"Officer",purchase_date:"2018-02-22",purchase_price:675000,deposit:67500,property_type:"House",beds:4,baths:2,land:515,status:"owner-occupier",notes:"Derek got a job offer in Brisbane — they are seriously considering a move interstate. Shannon is on the fence. They have two kids in primary school which complicates things. Derek mentioned he would prefer to sell before they decide on the move rather than rent it out. Very warm, good relationship with Cameron.",last_contact_date:"2025-02-14"},
  {id:5013,agent_name:"Cameron Knoll",name:"Jessica Tang",phone:"0433 556 778",email:"j.tang.property@gmail.com",purchase_address:"62 Hampton Park Drive, Narre Warren South",suburb:"Narre Warren South",purchase_date:"2021-03-12",purchase_price:890000,deposit:89000,property_type:"House",beds:5,baths:3,land:621,status:"owner-occupier",notes:"Jessica went through a divorce last year. The house is far too big for one person now. She works in finance in the city and is looking at a low-maintenance apartment or townhouse in Berwick or Narre Warren South. She's emotionally ready to move but practical about timing — wants to sell in spring when the market is better.",last_contact_date:"2025-04-20"},
  {id:5014,agent_name:"Cameron Knoll",name:"Kevin & Linda Park",phone:"0412 445 667",email:"kevinpark.invest@hotmail.com",purchase_address:"5 Sunridge Place, Berwick",suburb:"Berwick",purchase_date:"2015-10-28",purchase_price:625000,deposit:125000,property_type:"House",beds:4,baths:2,land:585,status:"investor",notes:"Kevin and Linda own three investment properties — this is one of them. Linda handles the portfolio management. She rang last quarter asking about the suburb trends. They are considering selling this one because the rental yield has softened and they want to invest in regional Victoria instead. Very process-driven, will want a full CMA.",last_contact_date:"2024-12-01"},
  {id:5015,agent_name:"Cameron Knoll",name:"Chris & Amanda Brown",phone:"0416 778 990",email:"cabrown.family@gmail.com",purchase_address:"72 Princes Highway, Hallam",suburb:"Hallam",purchase_date:"2016-09-05",purchase_price:520000,deposit:52000,property_type:"House",beds:3,baths:2,land:385,status:"owner-occupier",notes:"Chris works in trade sales, Amanda is a bookkeeper working from home. They have a 10-year-old and a 7-year-old. The 3-bed in Hallam is feeling cramped — Amanda needs a proper office. They've been driving around Officer and Berwick on weekends looking at open homes. Very active buyers, just need to make the sale decision first.",last_contact_date:"2025-01-22"},
  {id:5016,agent_name:"Cameron Knoll",name:"Mel & Brad Foster",phone:"0403 112 334",email:"fostermelb@gmail.com",purchase_address:"29 Grandview Boulevard, Officer",suburb:"Officer",purchase_date:"2020-12-10",purchase_price:730000,deposit:73000,property_type:"House",beds:4,baths:3,land:490,status:"owner-occupier",notes:"Mel and Brad have a 2-year-old and Mel is expecting their second. Brad works in construction management. Their current 4-bed is great but they'd love an extra bedroom for a dedicated study/craft room for Mel. Budget is tight so they'd need to sell first. Brad is a slow decision maker — Mel drives the property conversations.",last_contact_date:"2024-10-15"},
  {id:5017,agent_name:"Cameron Knoll",name:"Lisa & Graham Scott",phone:"0418 556 778",email:"scottfamily.berwick@gmail.com",purchase_address:"14 Sherwood Way, Berwick",suburb:"Berwick",purchase_date:"2017-08-04",purchase_price:810000,deposit:162000,property_type:"House",beds:5,baths:3,land:740,status:"owner-occupier",notes:"Lisa and Graham are both in their mid-50s — youngest daughter just moved to Melbourne CBD. Graham is thinking about semi-retirement. Lisa said at our last catch-up 'when the time is right, we'll downsize.' The 5-bedroom is enormous for two people. Graham does woodworking in the garage so he'd want a new place with a decent shed.",last_contact_date:"2024-07-10"},
  {id:5018,agent_name:"Cameron Knoll",name:"Sanjay Kumar",phone:"0488 223 445",email:"s.kumar.property@gmail.com",purchase_address:"14 Wattle Grove Crescent, Cranbourne",suburb:"Cranbourne",purchase_date:"2018-06-14",purchase_price:495000,deposit:49500,property_type:"Townhouse",beds:3,baths:2,land:220,status:"investor",notes:"Sanjay is an IT contractor, lives in Carlton. This townhouse has been rented at $390/wk but the body corp fees have crept up to $3,200/year. Net yield is softer than he'd like. He told me at a function last year that he was considering selling in 2025-2026 and moving the capital into shares. Needs a solid comparable sales analysis.",last_contact_date:"2024-05-10"},
  {id:5019,agent_name:"Cameron Knoll",name:"Danny & Trish Watts",phone:"0420 667 889",email:"dwatts1958@hotmail.com",purchase_address:"8 Parkview Terrace, Narre Warren South",suburb:"Narre Warren South",purchase_date:"2016-03-15",purchase_price:650000,deposit:130000,property_type:"House",beds:4,baths:2,land:605,status:"owner-occupier",notes:"Danny worked at Ford Broadmeadows for 30 years, now retired. Trish is a part-time florist. Both in their early 60s. Kids all grown up and interstate. Danny mentioned his knees aren't great so stairs are becoming an issue — they want something single-level, low maintenance, ideally closer to the lakes. Very genuine people, extremely loyal.",last_contact_date:"2024-09-12"},
  {id:5020,agent_name:"Cameron Knoll",name:"Lucy Chen",phone:"0400 667 889",email:"lucychen.au@gmail.com",purchase_address:"38 Sunbury Road, Endeavour Hills",suburb:"Endeavour Hills",purchase_date:"2019-04-09",purchase_price:680000,deposit:68000,property_type:"House",beds:4,baths:2,land:510,status:"investor",notes:"Lucy moved to Brisbane two years ago for work and has been renting this out since. She's paying a PM fee and has had maintenance issues — hot water system replaced last year. She's been asking friends whether it's a good time to sell. Emotionally detached from the property, primarily interested in the net proceeds figure.",last_contact_date:"2024-11-05"},
  {id:5021,agent_name:"Cameron Knoll",name:"Ben & Kate Murray",phone:"0411 889 001",email:"murrayhouse2021@gmail.com",purchase_address:"55 Ashwood Drive, Officer",suburb:"Officer",purchase_date:"2021-06-22",purchase_price:795000,deposit:79500,property_type:"House",beds:4,baths:2,land:465,status:"owner-occupier",notes:"Ben is a high school teacher, Kate is a marketing manager. Second baby due in four months. They'd love a 5th bedroom for a nursery + study. Ben mentioned they've been on a few open homes but haven't found the right property yet. Kate said she follows the Berwick market closely on Domain. They're realistic and not in a rush.",last_contact_date:"2025-04-01"},
  {id:5022,agent_name:"Cameron Knoll",name:"Steve & Di Lawson",phone:"0417 334 556",email:"di.lawson@gmail.com",purchase_address:"77 Canberra Street, Berwick",suburb:"Berwick",purchase_date:"2013-05-18",purchase_price:430000,deposit:86000,property_type:"House",beds:4,baths:2,land:630,status:"owner-occupier",notes:"Steve had a health scare last year — triple bypass. He's fully recovered but it changed their priorities. Di has been pushing to downsize to something manageable. The garden is high-maintenance and they both want to travel more. They have a lot of equity and Di mentioned a 2-bed villa in Berwick Village would be perfect. Di will make the call.",last_contact_date:"2025-03-28"},
  {id:5023,agent_name:"Cameron Knoll",name:"Jack Lam",phone:"0422 334 556",email:"j.lam.invest@gmail.com",purchase_address:"101 Clyde Road, Clyde North",suburb:"Clyde North",purchase_date:"2020-08-18",purchase_price:760000,deposit:76000,property_type:"House",beds:5,baths:3,land:448,status:"investor",notes:"Jack is a pharmacist who bought this new estate property as an IP. It's appreciated strongly in 4 years. He mentioned at a property seminar he attended (I was a speaker) that he was watching the market for the right time to sell and reinvest in commercial property. Methodical thinker, responds well to data. CGT planning is important to him.",last_contact_date:"2025-02-28"},
  {id:5024,agent_name:"Cameron Knoll",name:"Natalie & Brad Thompson",phone:"0405 778 990",email:"nbthompson.property@gmail.com",purchase_address:"9 Ironbark Circuit, Narre Warren South",suburb:"Narre Warren South",purchase_date:"2022-02-28",purchase_price:920000,deposit:184000,property_type:"House",beds:4,baths:2,land:512,status:"owner-occupier",notes:"Natalie and Brad bought this brand new in 2022 — stunning build, they love it. But Brad just got a significant promotion that requires a move to Sydney. They are torn. Natalie would prefer to rent it out but Brad thinks they should sell while the market is strong and buy something equally good in Sydney. Timing is the main constraint — Brad starts in September.",last_contact_date:"2025-04-30"},
  {id:5025,agent_name:"Cameron Knoll",name:"Peter & Robyn Clarke",phone:"0414 223 445",email:"pclarke.berwick@gmail.com",purchase_address:"41 Macquarie Drive, Berwick",suburb:"Berwick",purchase_date:"2014-04-22",purchase_price:575000,deposit:115000,property_type:"House",beds:4,baths:2,land:615,status:"owner-occupier",notes:"Peter is a retired schoolteacher, Robyn is a librarian going part-time this year. Both kids have long since left home. The garden backs onto the reserve which they love, but the 4-bed is just too much house. They've been talking about selling 'in the next year or two' for about three years now. Peter is the hesitant one. Robyn told me privately she's ready now.",last_contact_date:"2024-08-20"},
  {id:5026,agent_name:"Cameron Knoll",name:"Darren & Kylie Holt",phone:"0408 112 334",email:"dkyholt@gmail.com",purchase_address:"6 Ramsay Court, Berwick",suburb:"Berwick",purchase_date:"2019-07-20",purchase_price:680000,deposit:68000,property_type:"House",beds:3,baths:2,land:450,status:"buyer→landlord",notes:"Darren and Kylie have outgrown their 3-bed since having a third kid. They've been seriously looking at 4-5 bed homes in Berwick or Narre Warren South. Kylie is keen to KEEP the Ramsay Court house and rent it out — she said 'it's basically paid itself off.' Darren is on the fence but warming to the idea. They need to understand the rental yield and whether the bank will allow them to hold both. Great relationship — very open to advice.",last_contact_date:"2025-02-10"},
  {id:5027,agent_name:"Cameron Knoll",name:"Tim & Alicia Nguyen",phone:"0421 445 667",email:"timalivianguyen@gmail.com",purchase_address:"23 Huntington Drive, Officer",suburb:"Officer",purchase_date:"2018-11-14",purchase_price:650000,deposit:65000,property_type:"House",beds:4,baths:2,land:510,status:"buyer→landlord",notes:"Tim is a civil engineer, Alicia is a pharmacist. No kids yet but they're actively trying. They've built up solid equity and Tim mentioned at a BBQ that he wants to buy a new place and keep this one — he calls it 'building a passive income portfolio one house at a time.' Very financially savvy. Alicia is more conservative and wants to clear the mortgage on the current place first. The conversation is ongoing.",last_contact_date:"2025-01-05"},
  {id:5028,agent_name:"Cameron Knoll",name:"Mark Stellios",phone:"0414 778 990",email:"mark.stellios@outlook.com",purchase_address:"48 Junction Road, Narre Warren South",suburb:"Narre Warren South",purchase_date:"2016-04-08",purchase_price:590000,deposit:118000,property_type:"House",beds:4,baths:2,land:572,status:"buyer→landlord",notes:"Mark is divorced, kids are every second week. He wants to upsize to a 5-bed for when he has the kids (his partner Amy moves in part-time). His plan is to keep the current 4-bed as a rental — his brother offered to manage it informally. He's got strong equity and the bank pre-approval looks likely. Mark is decisive when he's ready to move. Needs a property with a guest room and double garage.",last_contact_date:"2024-12-20"},
  {id:5029,agent_name:"Cameron Knoll",name:"Sophie & Aaron Walsh",phone:"0433 223 445",email:"soph.walsh.au@gmail.com",purchase_address:"12 Crescent Drive, Berwick",suburb:"Berwick",purchase_date:"2020-09-11",purchase_price:745000,deposit:74500,property_type:"House",beds:4,baths:2,land:495,status:"buyer→landlord",notes:"Sophie and Aaron both work in healthcare — Sophie is a midwife, Aaron is a paramedic. No kids. They're high-income earners and want to use their equity to start a property portfolio. They attended one of Cameron's open homes in Pakenham out of curiosity and asked lots of smart questions. Their plan is to buy a second property and eventually have two IPs. Need guidance on which strategy makes more sense: sell vs hold.",last_contact_date:"2025-03-15"},
  {id:5030,agent_name:"Cameron Knoll",name:"Greg & Denise Hoffman",phone:"0405 334 556",email:"greghoffman58@bigpond.com",purchase_address:"35 Ferndale Close, Berwick",suburb:"Berwick",purchase_date:"2017-02-28",purchase_price:710000,deposit:142000,property_type:"House",beds:4,baths:2,land:620,status:"buyer→landlord",notes:"Greg and Denise are empty nesters. Youngest finished Year 12 last year. Denise's mother recently moved to a retirement village which has freed up a lot of their emotional bandwidth. They're considering a sea change to Inverloch or Wonthaggi — Greg's dream is to retire to the coast by 60 (he's 57). Plan is to keep the Berwick house as a rental and buy something smaller on the coast. Very open to a full strategy conversation.",last_contact_date:"2025-04-05"},
  {id:5031,agent_name:"Cameron Knoll",name:"Chloe & James Parker",phone:"0425 889 001",email:"chloe.jamesparker@gmail.com",purchase_address:"9 Westmore Way, Clyde North",suburb:"Clyde North",purchase_date:"2021-02-17",purchase_price:820000,deposit:82000,property_type:"House",beds:4,baths:2,land:448,status:"buyer→landlord",notes:"Chloe and James are both in their early 30s — Chloe is a UX designer, James is a software developer at Seek. They bought new in Clyde North's Eliston estate. They've been talking about moving to Berwick or Narre Warren South for better school zoning for their daughter (starting school in 2027). Their preference is to keep Clyde North as an IP and buy the family home. Mortgage broker is already on board. Just need to find the right property.",last_contact_date:"2025-05-01"},
  {id:5032,agent_name:"Cameron Knoll",name:"Ian & Cheryl Broadbent",phone:"0416 001 223",email:"ianbroadbent.berwick@gmail.com",purchase_address:"19 Silkwood Rise, Berwick",suburb:"Berwick",purchase_date:"2015-06-12",purchase_price:645000,deposit:129000,property_type:"House",beds:4,baths:2,land:598,status:"buyer→seller",notes:"Ian and Cheryl bought through Cameron in 2015. Both kids are now at uni interstate. They've been watching the market for about 18 months. Ian called last month and said 'we're ready when you are.' Cheryl wants to sell before winter and move into a low-maintenance villa in Berwick. Ian is fully on board. They are one of Cameron's warmest listings — just needs the call to confirm appraisal date.",last_contact_date:"2025-05-10"},
  {id:5033,agent_name:"Cameron Knoll",name:"Raj & Priya Sharma",phone:"0413 667 889",email:"rajpriya.sharma@gmail.com",purchase_address:"67 Outlook Drive, Narre Warren South",suburb:"Narre Warren South",purchase_date:"2016-08-30",purchase_price:720000,deposit:144000,property_type:"House",beds:5,baths:3,land:670,status:"buyer→seller",notes:"Raj is a pharmacist, Priya runs a childcare centre. Both born in India, highly community-oriented. Their three kids are grown up now. Priya messaged two months ago asking for a market appraisal — she said 'we've been here long enough, time to let someone else enjoy it.' They want to move to a townhouse in the Berwick Village precinct. Raj wants to understand CGT implications first. Very motivated to act in the next 3 months.",last_contact_date:"2025-04-15"},
  {id:5034,agent_name:"Cameron Knoll",name:"Nicole Harrison",phone:"0402 556 778",email:"nicole.harrison.au@gmail.com",purchase_address:"53 Cedar Creek Road, Harkaway",suburb:"Harkaway",purchase_date:"2018-03-22",purchase_price:950000,deposit:190000,property_type:"Acreage",beds:4,baths:2,land:4200,status:"buyer→seller",notes:"Nicole is a senior account manager at ANZ, recently separated. She bought the Harkaway acreage with her ex — managing 4,200m² alone has become too much. She's emotionally done with the property and wants a clean start. Looking at a townhouse or modern home in Berwick or Officer. She's given herself a firm deadline of end of 2026. Very organised, will want clear process steps. Handle with sensitivity — separation is recent.",last_contact_date:"2025-03-05"},
  {id:5035,agent_name:"Cameron Knoll",name:"Brendan & Jo Ellis",phone:"0417 334 556",email:"brendanjoellis@hotmail.com",purchase_address:"8 Wentworth Boulevard, Officer",suburb:"Officer",purchase_date:"2019-04-15",purchase_price:760000,deposit:76000,property_type:"House",beds:4,baths:2,land:530,status:"buyer→seller",notes:"Brendan drives trucks interstate, Jo is a teacher's aide at Berwick College. Their youngest just got a full footy scholarship in WA and is moving in July. Jo mentioned she cried about it but also said 'time to sell the big house.' They want to move to a low-maintenance 3-bed in Pakenham closer to Jo's mum. Brendan is away a lot so Jo handles the house stuff. Very genuine and warm — good relationship from when they bought.",last_contact_date:"2025-04-28"},
  {id:5036,agent_name:"Cameron Knoll",name:"Andrew Kim",phone:"0488 112 334",email:"andrew.kim.au@gmail.com",purchase_address:"14 Beauchamp Road, Berwick",suburb:"Berwick",purchase_date:"2020-07-01",purchase_price:815000,deposit:163000,property_type:"House",beds:4,baths:2,land:540,status:"buyer→seller",notes:"Andrew is a data scientist at Telstra. He bought this property when he was in a serious relationship — that didn't work out. He's been living here alone for the past 2 years and has now made the call to sell and move closer to the CBD. He's very analytical — expects a full comp analysis before listing. He'll move fast once he's satisfied with the data. Has already spoken to a mortgage broker about buying in Fitzroy North.",last_contact_date:"2025-05-15"},
  {id:5037,agent_name:"Cameron Knoll",name:"Mick & Tracey O'Sullivan",phone:"0403 778 990",email:"osullivanberwick@gmail.com",purchase_address:"26 Sandalwood Grove, Berwick",suburb:"Berwick",purchase_date:"2014-09-16",purchase_price:540000,deposit:108000,property_type:"House",beds:4,baths:2,land:635,status:"buyer→seller",notes:"Mick runs an electrical contracting business, Tracey is a dental receptionist. They've owned this 11 years and renovated the kitchen and bathrooms beautifully. Tracey called last week to say they're 'definitely listing this year.' They want to buy in Somerville or Mornington to be near Tracey's parents. Mick wants to make sure they get top dollar — he's proud of what they've done to the place. Appraisal conversation is overdue.",last_contact_date:"2025-05-18"},
  {id:5038,agent_name:"Cameron Knoll",name:"Yuki & David Tanaka",phone:"0431 223 445",email:"yukitanaka.melb@gmail.com",purchase_address:"4 Stonybrook Close, Narre Warren",suburb:"Narre Warren",purchase_date:"2017-05-30",purchase_price:685000,deposit:137000,property_type:"House",beds:4,baths:2,land:560,status:"buyer→seller",notes:"Yuki is a nurse manager, David works in IT security. They have two high-school kids. David got offered a 2-year secondment at Microsoft in Sydney, which they're taking. They want to sell the Narre Warren house before they go — too much risk leaving it vacant or dealing with tenants from interstate. Very organised, want a smooth sale process. Yuki is the main point of contact. Target departure is August/September.",last_contact_date:"2025-04-12"},
  {id:5039,agent_name:"Cameron Knoll",name:"Josh & Amber Reid",phone:"0407 556 778",email:"joshamber.reid@gmail.com",purchase_address:"Renting — 15 Fairway Drive, Berwick",suburb:"Berwick",purchase_date:"2025-01-01",purchase_price:0,deposit:60000,property_type:"House",beds:0,baths:0,land:0,status:"renter→buyer",notes:"Josh and Amber are renting in Berwick at $570/wk. Josh is a carpenter, Amber is a bookkeeper. They've been saving for 4 years and now have a $60k deposit plus FHOG. They attended Cameron's open home on Somerfield Circuit earlier this year and were well-researched. Pre-approval in progress through their broker. Amber has a Domain alert set for every new listing. They're very close to buying — budget around $680k-$720k, want at least 450m² land.",last_contact_date:"2025-05-02"},
  {id:5040,agent_name:"Cameron Knoll",name:"Priya Nair",phone:"0422 889 001",email:"priyanair.melb@gmail.com",purchase_address:"Renting — 8 Rosewood Drive, Narre Warren South",suburb:"Narre Warren South",purchase_date:"2025-01-01",purchase_price:0,deposit:80000,property_type:"Unit",beds:0,baths:0,land:0,status:"renter→buyer",notes:"Priya is a solicitor who moved to Berwick for work 3 years ago and has been renting. She's single but wants to buy her own place — 'tired of paying someone else's mortgage,' she said. She has $80k saved and solid income. Looking for a 3-bed townhouse or standalone 3-bed in Berwick, Narre Warren South, or Officer. Maximum budget $750k. She attended two of Cameron's open homes and follows the market keenly. Will be a decisive buyer when she finds the right fit.",last_contact_date:"2025-03-20"},
  {id:5041,agent_name:"Cameron Knoll",name:"Sam & Ella Kovacs",phone:"0415 334 556",email:"samella.kovacs@gmail.com",purchase_address:"Renting — 42 McMahon Road, Berwick",suburb:"Berwick",purchase_date:"2025-01-01",purchase_price:0,deposit:55000,property_type:"House",beds:0,baths:0,land:0,status:"renter→buyer",notes:"Sam is a mechanic, Ella is a nurse at Casey Hospital. They have a 3-year-old daughter. Both 28 years old, renting for 5 years. They missed out on a property in Cranbourne North last year (outbid by $25k) and were devastated — that actually pushed them to get really serious. Pre-approval is confirmed at $650k. They want to stay in Berwick school zone. Ella is very emotionally invested in the process. Sam wants something with a double garage.",last_contact_date:"2025-04-22"},
  {id:5042,agent_name:"Cameron Knoll",name:"Tom & Grace Osei",phone:"0402 667 889",email:"tgosei@gmail.com",purchase_address:"Renting — 77 Princes Highway, Berwick",suburb:"Berwick",purchase_date:"2025-01-01",purchase_price:0,deposit:95000,property_type:"House",beds:0,baths:0,land:0,status:"renter→buyer",notes:"Tom is a project manager at a civil engineering firm, Grace is a speech therapist. Originally from Ghana, been in Australia 6 years. They're citizens now and fully ready to buy. $95k deposit, pre-approved to $820k. They attended an open home in Berwick and were extremely polite and thorough — asked great questions about school catchments and public transport. Want a 4-bed with room for Grace's parents to visit. In no rush but will move quickly for the right property.",last_contact_date:"2025-05-08"},
  {id:5043,agent_name:"Cameron Knoll",name:"Connor Byrne",phone:"0430 001 223",email:"connorbyrne.au@gmail.com",purchase_address:"Renting — 31 Fairview Boulevard, Officer",suburb:"Officer",purchase_date:"2025-01-01",purchase_price:0,deposit:45000,property_type:"Unit",beds:0,baths:0,land:0,status:"renter→buyer",notes:"Connor is 26, works as a diesel mechanic at a transport depot in Dandenong. Single, no kids. His dad encouraged him to get into property and he's taken it seriously. He's been renting for 3 years and has just hit the $45k mark. Eligible for FHOG and First Home Guarantee (5% deposit). He's very motivated but a little nervous — first-time buyer, first in family. Wants a modest 3-bed in Officer or Pakenham around $580k-$620k. Will need hand-holding through the process.",last_contact_date:"2025-03-30"},
  {id:5044,agent_name:"Cameron Knoll",name:"Vikram & Lena Bhat",phone:"0412 778 990",email:"v.bhat.melb@gmail.com",purchase_address:"Renting — 18 Parkside Court, Berwick",suburb:"Berwick",purchase_date:"2025-01-01",purchase_price:0,deposit:120000,property_type:"House",beds:0,baths:0,land:0,status:"renter→buyer",notes:"Vikram is an anaesthetist at Monash, Lena is a GP. Dual high income, been renting by choice while establishing their careers. They now have $120k saved and are ready to buy a quality family home. Budget $950k–$1.1m. Looking for something in a premium Berwick street — Maranatha Estate or similar. They are particular about fit and finish and will take their time. They want Cameron's honest suburb-level advice, not a sales pitch. Treat them as peers.",last_contact_date:"2025-04-30"},
  {id:5045,agent_name:"Cameron Knoll",name:"Ross & Patricia McLeod",phone:"0419 445 667",email:"ross.mcleod.berwick@gmail.com",purchase_address:"66 Silkwood Rise, Berwick",suburb:"Berwick",purchase_date:"2015-07-14",purchase_price:780000,deposit:156000,property_type:"House",beds:5,baths:3,land:720,status:"buyer→downsizer",notes:"Ross is a retired dentist, Patricia a retired teacher. Both 64. Three adult kids all interstate. Ross has been talking about downsizing for two years but Patricia is emotionally attached to the garden. She recently said 'I think I'm ready now' — which is a big shift. They want a single-level 2 or 3-bed in Berwick Village with a courtyard or small garden. No stairs is non-negotiable for Patricia (hip replacement due next year). Strong financial position — property fully paid off.",last_contact_date:"2024-11-15"},
  {id:5046,agent_name:"Cameron Knoll",name:"Phil & Margaret Hart",phone:"0418 001 223",email:"p.hart.1960@hotmail.com",purchase_address:"34 Grandview Boulevard, Officer",suburb:"Officer",purchase_date:"2016-10-20",purchase_price:725000,deposit:145000,property_type:"House",beds:5,baths:2,land:695,status:"buyer→downsizer",notes:"Phil worked as a plumber for 40 years, now retired. Margaret still does casual work at Coles. They bought the 5-bed when all four kids were still at home. Now it's just them rattling around. Phil mentioned the upkeep is 'killing him' — gutters, painting, lawns. They've been talking to some of the other couples at Phil's Men's Shed about the downsizing process. Want something manageable — 2-bed + study, lock up and leave, near a golf course ideally.",last_contact_date:"2024-10-25"},
  {id:5047,agent_name:"Cameron Knoll",name:"Cheryl Donaldson",phone:"0423 334 556",email:"cheryl.donaldson59@gmail.com",purchase_address:"7 Yarrabee Way, Berwick",suburb:"Berwick",purchase_date:"2014-03-07",purchase_price:495000,deposit:99000,property_type:"House",beds:4,baths:2,land:580,status:"buyer→downsizer",notes:"Cheryl is a widow — husband Trevor passed away 18 months ago after a long illness. She's managing OK but said the big house is lonely and expensive to run. Both daughters have encouraged her to downsize to something near the Berwick Village strip. She attends the Berwick bowling club twice a week so she wants to stay close. Looking for a 2-bed villa or ground floor apartment. Proceeds from sale will top up her retirement savings. Handle with care and warmth — she trusts Cameron implicitly.",last_contact_date:"2025-02-22"},
  {id:5048,agent_name:"Cameron Knoll",name:"Barry & Anne Whitfield",phone:"0411 556 778",email:"whitfieldanne@gmail.com",purchase_address:"51 Somerfield Circuit, Berwick",suburb:"Berwick",purchase_date:"2017-01-18",purchase_price:855000,deposit:171000,property_type:"House",beds:5,baths:3,land:700,status:"buyer→downsizer",notes:"Barry is a retired accountant, Anne runs a small craft business online. Son in London, daughter in Brisbane. They're both 68 and ready to right-size. Barry wants to free up capital for travel — 'we want to see Europe properly while our knees still work,' he told Cameron at a function. Anne has been looking at townhouses near Berwick's high street. They're not in a rush but they're definitely in the mindset. A well-timed appraisal conversation would be very well received.",last_contact_date:"2024-09-08"},
  {id:5049,agent_name:"Cameron Knoll",name:"Norm & Val Perkins",phone:"0414 889 001",email:"normval.perkins@bigpond.com",purchase_address:"28 Hawthorn Park Drive, Narre Warren South",suburb:"Narre Warren South",purchase_date:"2013-09-11",purchase_price:520000,deposit:104000,property_type:"House",beds:4,baths:2,land:610,status:"buyer→downsizer",notes:"Norm worked at the council as an engineer, Val was a school librarian. Both retired. Four kids, all in their 30s and 40s, living across Melbourne. They bought through Cameron in 2013 when Cameron was just starting out — one of his earliest clients. Val mentioned at a community event that they were 'giving serious thought to downsizing.' Strong loyalty to Cameron. Have referred two people to him. Would be a meaningful listing and a good word-of-mouth opportunity.",last_contact_date:"2024-07-30"},
  {id:5050,agent_name:"Cameron Knoll",name:"Terry & Bev Cassidy",phone:"0420 223 445",email:"tncassidy@gmail.com",purchase_address:"16 Lakewood Avenue, Officer",suburb:"Officer",purchase_date:"2018-05-25",purchase_price:770000,deposit:154000,property_type:"House",beds:5,baths:3,land:660,status:"buyer→downsizer",notes:"Terry and Bev bought this 5-bed thinking the extended family would use it — that plan changed. Now it's just them. Terry has a chronic back condition and the stairs are a real problem. Bev mentioned she'd prefer a unit or single-storey townhouse in a complex with low maintenance. Their youngest still visits on weekends so they want at least a 2-bed with a quality spare room. Very pragmatic and process-focused. Terry will want a clear action plan and timeline before committing.",last_contact_date:"2025-03-12"},
  // Newer Cameron buyers (5051-5088)
  {id:5051,agent_name:"Cameron Knoll",name:"David & Karen Hollis",phone:"0418 234 567",email:"k.hollis.fam@gmail.com",purchase_address:"31 Avondale Street",suburb:"Officer",purchase_date:"2025-05-24",purchase_price:1510000,deposit:302000,property_type:"House",beds:4,baths:3,land:650,status:"owner-occupier",notes:"David is a civil engineer, Karen a part-time nurse. Bought Avondale as their forever house after upsizing from Hampton Park. Great backyard for the kids.",last_contact_date:"2025-06-22"},
  {id:5052,agent_name:"Cameron Knoll",name:"Liam & Sienna Doyle",phone:"0421 887 334",email:"liamdoyle.au@gmail.com",purchase_address:"21A Slingsby Avenue",suburb:"Beaconsfield",purchase_date:"2025-06-17",purchase_price:410000,deposit:82000,property_type:"House",beds:3,baths:2,land:355,status:"owner-occupier",notes:"First home buyers. Liam is an apprentice plumber, Sienna a vet nurse. Very budget-conscious, loved the low-maintenance block.",last_contact_date:"2025-07-15"},
  {id:5053,agent_name:"Cameron Knoll",name:"Michael & Tina Chen",phone:"0411 567 890",email:"m.chen.property@outlook.com",purchase_address:"1 Battalion Road",suburb:"Berwick",purchase_date:"2025-07-08",purchase_price:705000,deposit:141000,property_type:"House",beds:4,baths:3,land:490,status:"owner-occupier",notes:"Michael in IT, Tina a school teacher. Upgraded from Officer. Two young kids, wanted a good school zone.",last_contact_date:"2025-08-06"},
  {id:5054,agent_name:"Cameron Knoll",name:"Sandra & Greg Moore",phone:"0422 891 234",email:"sandra.moore2@gmail.com",purchase_address:"3 Pembroke Court",suburb:"Berwick",purchase_date:"2025-08-12",purchase_price:665000,deposit:133000,property_type:"House",beds:3,baths:2,land:430,status:"owner-occupier",notes:"Sandra and Greg bought Pembroke for the quiet court location. Both work in healthcare. Looking to upsize in 5 years as family grows.",last_contact_date:"2025-09-10"},
  {id:5055,agent_name:"Cameron Knoll",name:"James & Lisa Thompson",phone:"0404 123 456",email:"jlthompson@hotmail.com",purchase_address:"11 Coachella Way",suburb:"Berwick",purchase_date:"2025-09-03",purchase_price:720000,deposit:72000,property_type:"House",beds:3,baths:2,land:560,status:"owner-occupier",notes:"James a boilermaker, Lisa in accounting. Bought as their family home. Would consider upgrading if the right property comes up in 3-4 years.",last_contact_date:"2025-10-02"},
  {id:5056,agent_name:"Cameron Knoll",name:"Robert & Kym Patel",phone:"0431 678 901",email:"rob.patel@gmail.com",purchase_address:"55 Armitage Drive",suburb:"Narre Warren South",purchase_date:"2025-09-22",purchase_price:895000,deposit:179000,property_type:"House",beds:5,baths:2,land:890,status:"owner-occupier",notes:"Robert runs a small construction business, Kym a pharmacist. The 5-bed on Armitage was their forever home. Robert loves the big land — keeps bees in the backyard.",last_contact_date:"2025-10-20"},
  {id:5057,agent_name:"Cameron Knoll",name:"Sarah & Tom Mitchell",phone:"0413 445 678",email:"smitchell.family@gmail.com",purchase_address:"29 Charleston Chase",suburb:"Berwick",purchase_date:"2025-10-04",purchase_price:770000,deposit:154000,property_type:"House",beds:4,baths:2,land:560,status:"owner-occupier",notes:"Sarah and Tom have two daughters in primary school. Chose Berwick for the school zones. Sarah is a paediatrician, Tom a project manager.",last_contact_date:"2025-11-03"},
  {id:5058,agent_name:"Cameron Knoll",name:"Wei & Helen Zhang",phone:"0408 990 112",email:"weizhang.invest@outlook.com",purchase_address:"74 Wurundjeri Boulevard",suburb:"Berwick",purchase_date:"2025-10-28",purchase_price:840000,deposit:168000,property_type:"House",beds:4,baths:2,land:620,status:"investor",notes:"Wei and Helen own two other IPs. Purchased Wurundjeri as a buy-and-hold. Tenanted since settlement. Wei a civil engineer, Helen a dental practice manager.",last_contact_date:"2025-11-26"},
  {id:5059,agent_name:"Cameron Knoll",name:"Paul & Donna Donovan",phone:"0499 334 112",email:"pdonovan55@yahoo.com.au",purchase_address:"19 Embling Street",suburb:"Berwick",purchase_date:"2025-11-10",purchase_price:720000,deposit:72000,property_type:"House",beds:3,baths:2,land:520,status:"owner-occupier",notes:"Paul a plumber, Donna a classroom assistant. First family home. Three kids. Budget was tight — Embling Street ticked every box at a great price.",last_contact_date:"2025-12-08"},
  {id:5060,agent_name:"Cameron Knoll",name:"Anthony & Bec Nguyen",phone:"0455 334 667",email:"a.nguyen.prop@gmail.com",purchase_address:"23 Coachella Way",suburb:"Berwick",purchase_date:"2025-11-25",purchase_price:800000,deposit:160000,property_type:"House",beds:4,baths:2,land:580,status:"owner-occupier",notes:"Anthony an electrician, Bec in marketing. Upsized from a townhouse in Pakenham. Love the Berwick lifestyle. Mentioned wanting to invest in a couple of years.",last_contact_date:"2025-12-23"},
  {id:5061,agent_name:"Cameron Knoll",name:"Emma & Josh Wilson",phone:"0406 789 012",email:"emma.wilson.home@gmail.com",purchase_address:"11 Buchanan Road",suburb:"Berwick",purchase_date:"2025-12-08",purchase_price:680000,deposit:68000,property_type:"House",beds:3,baths:1,land:490,status:"owner-occupier",notes:"Emma and Josh are newly married — first home purchase. Emma in HR, Josh a tiler. Small backyard but perfect starter home in a great location.",last_contact_date:"2026-01-07"},
  {id:5062,agent_name:"Cameron Knoll",name:"Chris & Amanda Brown",phone:"0416 778 990",email:"cabrown.family@gmail.com",purchase_address:"5 Settlers Run Boulevard",suburb:"Berwick",purchase_date:"2025-12-16",purchase_price:815000,deposit:163000,property_type:"House",beds:4,baths:2,land:590,status:"owner-occupier",notes:"Chris a secondary teacher, Amanda a speech pathologist. Moved from Narre Warren. Love the estate atmosphere and proximity to good schools.",last_contact_date:"2026-01-14"},
  {id:5063,agent_name:"Cameron Knoll",name:"Mel & Brad Foster",phone:"0403 112 334",email:"fostermelb@gmail.com",purchase_address:"8 Langmore Lane",suburb:"Berwick",purchase_date:"2025-12-20",purchase_price:710000,deposit:142000,property_type:"House",beds:3,baths:2,land:430,status:"owner-occupier",notes:"Mel and Brad downsized from Cranbourne North after the kids left home. Both retired teachers. Very social, attend every street event.",last_contact_date:"2026-01-18"},
  {id:5064,agent_name:"Cameron Knoll",name:"Lisa & Graham Scott",phone:"0418 556 778",email:"scottfamily.berwick@gmail.com",purchase_address:"42 Silkwood Rise",suburb:"Berwick",purchase_date:"2026-01-09",purchase_price:840000,deposit:168000,property_type:"House",beds:4,baths:2,land:540,status:"owner-occupier",notes:"Lisa an ICU nurse, Graham a logistics manager. Second home — upgraded from Hampton Park. Two boys, love that the street is quiet and safe.",last_contact_date:"2026-02-07"},
  {id:5065,agent_name:"Cameron Knoll",name:"Danny & Trish Watts",phone:"0420 667 889",email:"dwatts1958@hotmail.com",purchase_address:"16 Cardinia Road",suburb:"Officer",purchase_date:"2026-01-14",purchase_price:780000,deposit:78000,property_type:"House",beds:4,baths:2,land:600,status:"owner-occupier",notes:"Danny is a diesel mechanic, Trish runs a home daycare. Bought Officer for the bigger block — Danny wanted a shed. Mentioned considering an investment later.",last_contact_date:"2026-02-12"},
  {id:5066,agent_name:"Cameron Knoll",name:"Steve & Di Lawson",phone:"0417 334 556",email:"di.lawson@gmail.com",purchase_address:"23 Peake Way",suburb:"Berwick",purchase_date:"2026-01-22",purchase_price:720000,deposit:72000,property_type:"House",beds:3,baths:2,land:450,status:"owner-occupier",notes:"Steve a carpenter, Di in office admin. Third home — upsized within Berwick. Familiar with the suburb and very loyal to the area.",last_contact_date:"2026-02-20"},
  {id:5067,agent_name:"Cameron Knoll",name:"Ben & Kate Murray",phone:"0411 889 001",email:"murrayhouse2021@gmail.com",purchase_address:"9 Morning Glory Avenue",suburb:"Berwick",purchase_date:"2026-01-29",purchase_price:810000,deposit:162000,property_type:"House",beds:4,baths:2,land:580,status:"owner-occupier",notes:"Ben a financial planner, Kate a midwife. Looking for a long-term family home. Very thorough buyers — asked great questions at the open home.",last_contact_date:"2026-02-27"},
  {id:5068,agent_name:"Cameron Knoll",name:"Sanjay & Priya Kumar",phone:"0488 223 445",email:"s.kumar.property@gmail.com",purchase_address:"14 Gloucester Avenue",suburb:"Berwick",purchase_date:"2026-02-04",purchase_price:740000,deposit:148000,property_type:"House",beds:3,baths:2,land:480,status:"owner-occupier",notes:"Sanjay a software developer, Priya a GP registrar. First Berwick home after renting in Melbourne. Very community-focused couple.",last_contact_date:"2026-03-05"},
  {id:5069,agent_name:"Cameron Knoll",name:"Jack & Rose Lam",phone:"0422 334 556",email:"j.lam.invest@gmail.com",purchase_address:"34 Hartsmere Drive",suburb:"Berwick",purchase_date:"2026-02-08",purchase_price:865000,deposit:173000,property_type:"House",beds:4,baths:2,land:621,status:"owner-occupier",notes:"Jack a structural engineer, Rose in HR management. Moved from Box Hill. Love the space Berwick offers. Mentioned talking about investment in future.",last_contact_date:"2026-03-10"},
  {id:5070,agent_name:"Cameron Knoll",name:"Peter & Robyn Clarke",phone:"0414 223 445",email:"pclarke.berwick@gmail.com",purchase_address:"28 Mansfield Street",suburb:"Berwick",purchase_date:"2026-02-18",purchase_price:890000,deposit:178000,property_type:"House",beds:4,baths:2,land:560,status:"owner-occupier",notes:"Peter a civil contractor, Robyn a primary school principal. Chose Berwick after looking in Officer and Beaconsfield. Love the community feel.",last_contact_date:"2026-03-18"},
  {id:5071,agent_name:"Cameron Knoll",name:"Darren & Kylie Holt",phone:"0408 112 334",email:"dkyholt@gmail.com",purchase_address:"6 Ridgewood Drive",suburb:"Berwick",purchase_date:"2026-02-25",purchase_price:1050000,deposit:210000,property_type:"House",beds:4,baths:3,land:640,status:"owner-occupier",notes:"Darren runs his own plumbing business, Kylie a dental hygienist. Traded up from Cranbourne North to get a premium property. Darren keen on an investment next.",last_contact_date:"2026-03-25"},
  {id:5072,agent_name:"Cameron Knoll",name:"Tim & Alicia Nguyen",phone:"0421 445 667",email:"timalivianguyen@gmail.com",purchase_address:"3 Yemaya Place",suburb:"Berwick",purchase_date:"2026-03-15",purchase_price:1090000,deposit:218000,property_type:"House",beds:4,baths:2,land:600,status:"owner-occupier",notes:"Tim a surgeon, Alicia an architect. Premium buyer. Tim mentioned wanting to downsize in 10 years once the kids are through school. Very well networked.",last_contact_date:"2026-04-14"},
  {id:5073,agent_name:"Cameron Knoll",name:"Mark & Julie Stellios",phone:"0414 778 990",email:"mark.stellios@outlook.com",purchase_address:"5 Ascot Rise",suburb:"Berwick",purchase_date:"2026-03-17",purchase_price:1260000,deposit:252000,property_type:"House",beds:4,baths:2,land:754,status:"owner-occupier",notes:"Mark owns a restaurant in the CBD, Julie an interior designer. Bought Ascot Rise for the large block and renovation potential. Premium lifestyle buyers.",last_contact_date:"2026-04-16"},
  {id:5074,agent_name:"Cameron Knoll",name:"Sophie & Aaron Walsh",phone:"0433 223 445",email:"soph.walsh.au@gmail.com",purchase_address:"19 Settlers Grove",suburb:"Berwick",purchase_date:"2026-03-27",purchase_price:890000,deposit:89000,property_type:"House",beds:4,baths:2,land:560,status:"owner-occupier",notes:"Sophie a nurse educator, Aaron a site supervisor. Third home — very knowledgeable about the market. Mentioned possibly investing in 12-18 months.",last_contact_date:"2026-04-25"},
  {id:5075,agent_name:"Cameron Knoll",name:"Greg & Denise Hoffman",phone:"0405 334 556",email:"greghoffman58@bigpond.com",purchase_address:"7 Buttonbush Lane",suburb:"Berwick",purchase_date:"2026-04-05",purchase_price:760000,deposit:152000,property_type:"House",beds:3,baths:2,land:430,status:"owner-occupier",notes:"Greg a retired teacher, Denise still working as a bookkeeper. Downsized from a larger Officer property. Bought Buttonbush for low maintenance and a good location.",last_contact_date:"2026-05-04"},
  {id:5076,agent_name:"Cameron Knoll",name:"Chloe & James Parker",phone:"0425 889 001",email:"chloe.jamesparker@gmail.com",purchase_address:"25 Grand Arch Way",suburb:"Berwick",purchase_date:"2026-04-10",purchase_price:1100000,deposit:220000,property_type:"House",beds:4,baths:2,land:680,status:"owner-occupier",notes:"Chloe a solicitor, James a senior accountant. Discerning buyers — inspected many properties. Grand Arch Way won them over with the street appeal.",last_contact_date:"2026-05-09"},
  {id:5077,agent_name:"Cameron Knoll",name:"Ian & Cheryl Broadbent",phone:"0416 001 223",email:"ianbroadbent.berwick@gmail.com",purchase_address:"11 Cheltenham Road",suburb:"Berwick",purchase_date:"2026-04-16",purchase_price:980000,deposit:196000,property_type:"House",beds:4,baths:2,land:590,status:"owner-occupier",notes:"Ian a building inspector, Cheryl a physiotherapist. Very thorough at the inspection. Ian checked every corner before bidding.",last_contact_date:"2026-05-15"},
  {id:5078,agent_name:"Cameron Knoll",name:"Raj & Priya Sharma",phone:"0413 667 889",email:"rajpriya.sharma@gmail.com",purchase_address:"44 Station Street",suburb:"Berwick",purchase_date:"2026-04-22",purchase_price:820000,deposit:164000,property_type:"House",beds:3,baths:2,land:430,status:"owner-occupier",notes:"Raj an IT consultant, Priya a pharmacist. Moved from Dandenong. Raj mentioned they may look to invest once they settle in.",last_contact_date:"2026-05-21"},
  {id:5079,agent_name:"Cameron Knoll",name:"Nicole & Brad Harrison",phone:"0402 556 778",email:"nicole.harrison.au@gmail.com",purchase_address:"17 Glengala Drive",suburb:"Berwick",purchase_date:"2026-04-29",purchase_price:1030000,deposit:206000,property_type:"House",beds:4,baths:2,land:620,status:"owner-occupier",notes:"Nicole a paediatric OT, Brad a mechanical engineer. Upsized from Hallam. Brad mentioned wanting an investment property once this one settles.",last_contact_date:"2026-05-28"},
  {id:5080,agent_name:"Cameron Knoll",name:"Brendan & Jo Ellis",phone:"0417 334 556",email:"brendanjoellis@hotmail.com",purchase_address:"3 Thirlmere Court",suburb:"Berwick",purchase_date:"2026-05-02",purchase_price:941000,deposit:188200,property_type:"House",beds:4,baths:2,land:612,status:"owner-occupier",notes:"Brendan a construction manager, Jo a radiographer. 26 registered bidders at auction. Brendan had been watching this pocket of Berwick for 18 months.",last_contact_date:"2026-06-01"},
  {id:5081,agent_name:"Cameron Knoll",name:"Andrew & Fiona Kim",phone:"0488 112 334",email:"andrew.kim.au@gmail.com",purchase_address:"11 Coach House Lane",suburb:"Beaconsfield",purchase_date:"2026-05-04",purchase_price:2111001,deposit:422200,property_type:"House",beds:5,baths:3,land:850,status:"owner-occupier",notes:"Andrew a senior law firm partner, Fiona a specialist GP. Prestige buyer. Coach House Lane is one of Beaconsfield's most sought-after streets.",last_contact_date:"2026-06-03"},
  {id:5082,agent_name:"Cameron Knoll",name:"Mick & Tracey O'Sullivan",phone:"0403 778 990",email:"osullivanberwick@gmail.com",purchase_address:"2 Brentwood Park Drive",suburb:"Berwick",purchase_date:"2026-05-08",purchase_price:1050000,deposit:210000,property_type:"House",beds:4,baths:2,land:580,status:"owner-occupier",notes:"Mick a project director, Tracey a speech therapist. Bought after months of searching. Love the leafy streetscape on Brentwood Park Drive.",last_contact_date:"2026-06-06"},
  {id:5083,agent_name:"Cameron Knoll",name:"Yuki & David Tanaka",phone:"0431 223 445",email:"yukitanaka.melb@gmail.com",purchase_address:"7 Wilson Park Drive",suburb:"Berwick",purchase_date:"2026-05-11",purchase_price:1100000,deposit:220000,property_type:"House",beds:4,baths:2,land:600,status:"investor",notes:"Yuki and David own three properties already. Bought Wilson Park Drive as a long-term hold given the strong rental demand in Berwick.",last_contact_date:"2026-06-10"},
  {id:5084,agent_name:"Cameron Knoll",name:"Josh & Amber Reid",phone:"0407 556 778",email:"joshamber.reid@gmail.com",purchase_address:"15 Alexia Drive",suburb:"Berwick",purchase_date:"2026-05-21",purchase_price:1270000,deposit:254000,property_type:"House",beds:4,baths:2,land:620,status:"owner-occupier",notes:"Josh a structural engineer, Amber a senior physiotherapist. Strong competing bids at auction. Josh mentioned they had been watching Alexia Drive for months.",last_contact_date:"2026-06-20"},
  {id:5085,agent_name:"Cameron Knoll",name:"Priya & Nikhil Nair",phone:"0422 889 001",email:"priyanair.melb@gmail.com",purchase_address:"48 President Road",suburb:"Narre Warren South",purchase_date:"2026-05-26",purchase_price:830000,deposit:166000,property_type:"House",beds:4,baths:2,land:640,status:"owner-occupier",notes:"Priya a cardiologist, Nikhil an accountant. Moved from Point Cook to be closer to family in SE Melbourne. Loved the block size on President Road.",last_contact_date:"2026-06-25"},
  {id:5086,agent_name:"Cameron Knoll",name:"Sam & Ella Kovacs",phone:"0415 334 556",email:"samella.kovacs@gmail.com",purchase_address:"125 Bellevue Drive",suburb:"Berwick",purchase_date:"2026-05-26",purchase_price:795000,deposit:159000,property_type:"House",beds:4,baths:2,land:610,status:"owner-occupier",notes:"Sam a site manager, Ella a teacher. Bellevue Drive was their top pick from day one. Mentioned considering an investment in 12 months.",last_contact_date:"2026-06-25"},
  {id:5087,agent_name:"Cameron Knoll",name:"Tom & Grace Osei",phone:"0402 667 889",email:"tgosei@gmail.com",purchase_address:"22 Birch Drive",suburb:"Berwick",purchase_date:"2026-05-28",purchase_price:880000,deposit:176000,property_type:"House",beds:4,baths:2,land:560,status:"owner-occupier",notes:"Tom a commercial draftsman, Grace a registered nurse. Bought after missing out at two previous auctions. Happy to have finally secured in Berwick.",last_contact_date:"2026-06-27"},
  {id:5088,agent_name:"Cameron Knoll",name:"Connor & Jess Byrne",phone:"0430 001 223",email:"connorbyrne.au@gmail.com",purchase_address:"8 Ramsay Court",suburb:"Berwick",purchase_date:"2026-05-30",purchase_price:850000,deposit:170000,property_type:"House",beds:4,baths:2,land:540,status:"owner-occupier",notes:"Connor a civil engineer, Jess a pharmacist. Young professional couple. Their first large family home after renting in Richmond for 5 years. Very motivated to settle.",last_contact_date:"2026-06-29"},
  // ── Manpreet Singh / Barry Plant Berwick (25 rows) ────────────────────────
  {id:7001,agent_name:"Manpreet Singh",name:"Kevin & Amita Sharma",phone:"0432 881 207",email:"amita.sharma@gmail.com",purchase_address:"34 Van Der Haar Avenue",suburb:"Berwick",purchase_date:"2020-08-14",purchase_price:645000,deposit:64500,property_type:"House",beds:4,baths:1,land:450,status:"owner-occupier",notes:"Kevin teaches at Berwick Secondary, Amita is in healthcare admin at Casey Hospital. Two kids — Aryan (4) and Kavya (2). Baby number three due January 2027. The house is already feeling cramped — Amita mentioned the kids are sharing a room and it is getting harder. They want a 4-bed with a proper study. Very motivated but nervous about the market. Kevin follows the Jack William Way sales closely — was really impressed with what Manpreet got for No. 40.",last_contact_date:"2025-04-22"},
  {id:7002,agent_name:"Manpreet Singh",name:"Jason Nakamura",phone:"0418 556 334",email:"jason.nakamura.invest@gmail.com",purchase_address:"33 Tilden Rise",suburb:"Cranbourne North",purchase_date:"2017-06-10",purchase_price:590000,deposit:118000,property_type:"House",beds:4,baths:2,land:510,status:"investor",notes:"Jason lives in Toorak. This is one of three IPs. Tenant lease on Tilden Rise expires June 2026. He is very numbers-focused and tracks property values obsessively — sent Manpreet a message after the 40 Jack William Way sale asking if the Berwick market had peaked. Jason has read about the CGT discount changes and mentioned he might want to sell before 2027 to lock in the discount. Responds to data, not emotion.",last_contact_date:"2025-05-02",personalisation_hook:"Jason, your Tilden Rise tenant just renewed for another 12 months. Yield is sitting at 4.2%."},
  {id:7003,agent_name:"Manpreet Singh",name:"Bill & Heather McCormack",phone:"0411 223 744",email:"hmc.berwick@bigpond.com",purchase_address:"10 Royal Crescent",suburb:"Beaconsfield",purchase_date:"2016-03-22",purchase_price:570000,deposit:114000,property_type:"House",beds:5,baths:2,land:750,status:"owner-occupier",notes:"Lovely couple. Bill is a retired school principal, Heather still does bookkeeping a couple days a week. Both kids have flown the nest — son in Sydney, daughter in London. Five-bed house on Royal Crescent is way too much for the two of them now. Bill told Manpreet at the school fete that he is ready when Heather is. Heather is getting closer — she has started looking at ground-floor apartments in Berwick Village. Garden maintenance is becoming a real issue for Bills back.",last_contact_date:"2025-03-15"},
  {id:7004,agent_name:"Manpreet Singh",name:"Thanh & Lily Vo",phone:"0403 119 865",email:"thanh.vo.property@gmail.com",purchase_address:"45 Tantallon Boulevard",suburb:"Beaconsfield",purchase_date:"2021-04-19",purchase_price:755000,deposit:75500,property_type:"House",beds:4,baths:2,land:560,status:"owner-occupier",notes:"Thanh is in logistics management, Lily is a dental hygienist. No kids yet but mentioned they want to start a family in the next year or two. They bought 45 Tantallon Boulevard just before the top of the market. Thanh was a bit worried for a while but the sale at 40 Jack William Way for $805K made him feel much better about the area. He messaged Manpreet the day after settlement to ask what Tantallon would be worth now. Not rushing, but definitely thinking about it.",last_contact_date:"2025-05-26"},
  {id:7005,agent_name:"Manpreet Singh",name:"Dan & Carly Crosbie",phone:"0427 490 612",email:"dancrosbie@hotmail.com",purchase_address:"12 Homestead Road",suburb:"Berwick",purchase_date:"2018-09-03",purchase_price:695000,deposit:139000,property_type:"House",beds:3,baths:2,land:510,status:"investor",notes:"Dan is a builder, Carly is a teacher at Kambrya College. Investment property — they live in Officer. Currently rented at $520/wk. Dan mentioned after the 15 Hartsmere Drive sale that he is thinking about selling to fund a duplex development in Pakenham. He has the skills to build it himself. Very pragmatic — he will move when the numbers make sense. Carly is supportive but wants to understand the tax position first.",last_contact_date:"2025-02-10"},
  {id:7006,agent_name:"Manpreet Singh",name:"Kevin & Linda Park",phone:"0412 445 667",email:"kevinpark.invest@hotmail.com",purchase_address:"4 Saintly Grove",suburb:"Berwick",purchase_date:"2025-09-10",purchase_price:847000,deposit:169400,property_type:"House",beds:4,baths:2,land:560,status:"owner-occupier",notes:"Kevin a construction project manager, Linda a school counsellor. Chose Saintly Grove for the quiet cul-de-sac. Kevin mentioned they'd look to invest in 2–3 years.",last_contact_date:"2025-10-09"},
  {id:7007,agent_name:"Manpreet Singh",name:"Frank & Maria Russo",phone:"0417 223 445",email:"russo.frank@bigpond.com",purchase_address:"121 Fleetwood Drive",suburb:"Narre Warren",purchase_date:"2025-09-16",purchase_price:804000,deposit:160800,property_type:"House",beds:4,baths:2,land:580,status:"owner-occupier",notes:"Frank a concreter, Maria a childcare director. Moved from Dandenong. Frank keen on an investment property once they settle.",last_contact_date:"2025-10-16"},
  {id:7008,agent_name:"Manpreet Singh",name:"Derek & Shannon O'Brien",phone:"0421 667 889",email:"shannobrien@gmail.com",purchase_address:"24 Balmaceda Court",suburb:"Berwick",purchase_date:"2025-09-23",purchase_price:780000,deposit:156000,property_type:"House",beds:4,baths:2,land:540,status:"owner-occupier",notes:"Derek a boilermaker, Shannon a nurse. Second home — upsized from a unit in Cranbourne. Very settled in Berwick with two primary school-age kids.",last_contact_date:"2025-10-23"},
  {id:7009,agent_name:"Manpreet Singh",name:"Jessica & Ryan Tang",phone:"0433 556 778",email:"j.tang.property@gmail.com",purchase_address:"7 Bangalay Place",suburb:"Berwick",purchase_date:"2025-10-02",purchase_price:862000,deposit:172400,property_type:"House",beds:3,baths:2,land:520,status:"owner-occupier",notes:"Jessica a marketing manager, Ryan a structural engineer. Bought Bangalay for the character and street appeal. Mentioned possibly selling in 5 years to upsize.",last_contact_date:"2025-11-01"},
  {id:7010,agent_name:"Manpreet Singh",name:"Kevin & Amita Sharma",phone:"0432 881 208",email:"amita.sharma2@gmail.com",purchase_address:"37 Bowler Avenue",suburb:"Clyde",purchase_date:"2025-10-07",purchase_price:610000,deposit:61000,property_type:"House",beds:4,baths:2,land:580,status:"investor",notes:"Kevin teaches at Berwick Secondary, Amita in admin. Bought Clyde as an investment — good rental yield in the area. First IP for the couple. Keen to chat about next steps.",last_contact_date:"2025-11-06"},
  {id:7011,agent_name:"Manpreet Singh",name:"Jason & Mei Nakamura",phone:"0418 556 335",email:"jason.nakamura.invest@gmail.com",purchase_address:"32 Ashfield Drive",suburb:"Berwick",purchase_date:"2025-10-08",purchase_price:835000,deposit:167000,property_type:"House",beds:4,baths:2,land:590,status:"investor",notes:"Jason lives in Toorak and owns several IPs. Bought 32 Ashfield Drive for strong capital growth potential. Very numbers-focused — asked about rental appraisals upfront.",last_contact_date:"2025-11-07"},
  {id:7012,agent_name:"Manpreet Singh",name:"Bill & Heather McCormack",phone:"0411 223 745",email:"hmc.berwick@bigpond.com",purchase_address:"5/147 Golf Links Road",suburb:"Berwick",purchase_date:"2025-10-20",purchase_price:740000,deposit:148000,property_type:"Unit",beds:4,baths:2,land:0,status:"investor",notes:"Lovely couple — Bill a retired engineer, Heather a nurse. The Golf Links unit is their third IP. Very comfortable buyers who know exactly what they want.",last_contact_date:"2025-11-19"},
  {id:7013,agent_name:"Manpreet Singh",name:"Thanh & Lily Vo",phone:"0403 119 866",email:"thanh.vo.property2@gmail.com",purchase_address:"70 Carnival Boulevard",suburb:"Berwick",purchase_date:"2025-11-04",purchase_price:687500,deposit:137500,property_type:"Unit",beds:4,baths:2,land:0,status:"owner-occupier",notes:"Thanh is in logistics, Lily a bookkeeper. First home buyers who found great value in the Carnival Blvd unit. Very happy with the community feel.",last_contact_date:"2025-12-04"},
  {id:7014,agent_name:"Manpreet Singh",name:"Dan & Carly Crosbie",phone:"0427 490 613",email:"dancrosbie2@hotmail.com",purchase_address:"7 Ashfield Drive",suburb:"Berwick",purchase_date:"2025-11-28",purchase_price:768000,deposit:153600,property_type:"House",beds:3,baths:1,land:490,status:"investor",notes:"Dan is a builder, Carly a real estate property manager. Bought 7 Ashfield Drive as an investment — Dan plans to renovate to add value. Very knowledgeable buyers.",last_contact_date:"2025-12-28"},
  {id:7015,agent_name:"Manpreet Singh",name:"Nick & Carla Ferraro",phone:"0418 990 223",email:"ncarlaferraro@gmail.com",purchase_address:"55 Mansfield Street",suburb:"Berwick",purchase_date:"2025-12-10",purchase_price:629000,deposit:62900,property_type:"Unit",beds:3,baths:1,land:0,status:"owner-occupier",notes:"Nick a chef, Carla a dental assistant. First home. Nick loved the low-maintenance lifestyle, Carla the proximity to cafes and the village.",last_contact_date:"2026-01-08"},
  {id:7016,agent_name:"Manpreet Singh",name:"Ross & Patricia McLeod",phone:"0419 445 668",email:"ross.mcleod.berwick@gmail.com",purchase_address:"6 Monarch Road",suburb:"Berwick",purchase_date:"2025-12-30",purchase_price:950000,deposit:190000,property_type:"House",beds:4,baths:2,land:620,status:"owner-occupier",notes:"Ross a senior project manager, Patricia a psychologist. Monarch Road was their dream home. Paid a premium but loved the design and location.",last_contact_date:"2026-01-29"},
  {id:7017,agent_name:"Manpreet Singh",name:"Phil & Margaret Hart",phone:"0418 001 224",email:"p.hart.1960@hotmail.com",purchase_address:"17B Sylvia Road",suburb:"Beaconsfield",purchase_date:"2026-01-20",purchase_price:720000,deposit:144000,property_type:"Unit",beds:3,baths:2,land:0,status:"owner-occupier",notes:"Phil a retired plumber, Margaret a hospital administrator. Downsized from a large Beaconsfield property. Low maintenance lifestyle at the top of their wish list.",last_contact_date:"2026-02-19"},
  {id:7018,agent_name:"Manpreet Singh",name:"Cheryl & Mark Donaldson",phone:"0423 334 557",email:"cheryl.donaldson2@gmail.com",purchase_address:"3 Jane Street",suburb:"Berwick",purchase_date:"2026-01-27",purchase_price:685000,deposit:137000,property_type:"Unit",beds:3,baths:1,land:0,status:"owner-occupier",notes:"Cheryl a nurse manager, Mark a bus driver. Bought 3 Jane Street as a lock-up-and-leave. Love that it's close to the Berwick Village cafes.",last_contact_date:"2026-02-26"},
  {id:7019,agent_name:"Manpreet Singh",name:"Barry & Anne Whitfield",phone:"0411 556 779",email:"whitfieldanne2@gmail.com",purchase_address:"47 Marija Crescent",suburb:"Berwick",purchase_date:"2026-02-27",purchase_price:920000,deposit:184000,property_type:"House",beds:4,baths:3,land:610,status:"owner-occupier",notes:"Barry a building certifier, Anne a secondary teacher. Marija Crescent had great street presence — was a competitive auction with multiple bidders.",last_contact_date:"2026-03-29"},
  {id:7020,agent_name:"Manpreet Singh",name:"Norm & Val Perkins",phone:"0414 889 002",email:"normval.perkins2@bigpond.com",purchase_address:"4 Riverglen Road",suburb:"Berwick",purchase_date:"2026-03-30",purchase_price:1035000,deposit:207000,property_type:"House",beds:5,baths:2,land:690,status:"owner-occupier",notes:"Norm a retired builder, Val a community nurse. Bought Riverglen for the large land and the prestige address. Norm keen to do some landscaping work himself.",last_contact_date:"2026-04-29"},
  {id:7021,agent_name:"Manpreet Singh",name:"Terry & Bev Cassidy",phone:"0420 223 446",email:"tncassidy2@gmail.com",purchase_address:"13 Jack William Way",suburb:"Berwick",purchase_date:"2026-03-31",purchase_price:1025000,deposit:205000,property_type:"House",beds:4,baths:2,land:620,status:"owner-occupier",notes:"Terry a telecommunications manager, Bev a radiographer. Jack William Way was their dream street. Researched the area thoroughly before bidding.",last_contact_date:"2026-04-30"},
  {id:7022,agent_name:"Manpreet Singh",name:"Vikram & Lena Bhat",phone:"0412 778 991",email:"v.bhat.melb2@gmail.com",purchase_address:"1 Ben Drive",suburb:"Pakenham",purchase_date:"2026-04-21",purchase_price:685000,deposit:68500,property_type:"House",beds:3,baths:1,land:490,status:"owner-occupier",notes:"Vikram a software engineer, Lena a physiotherapist. First home — chose Pakenham for affordability while still in Manny's area. Mentioned upgrading in a few years.",last_contact_date:"2026-05-21"},
  {id:7023,agent_name:"Manpreet Singh",name:"Lucy & Adam Chen",phone:"0400 667 890",email:"lucychen2.au@gmail.com",purchase_address:"19/44 King Street",suburb:"Pakenham",purchase_date:"2026-04-29",purchase_price:525000,deposit:52500,property_type:"Unit",beds:3,baths:1,land:0,status:"owner-occupier",notes:"Lucy a dental receptionist, Adam in retail management. First home buyers who loved the low entry price. Lucy mentioned they'll upgrade to a house in 3-4 years.",last_contact_date:"2026-05-29"},
  {id:7024,agent_name:"Manpreet Singh",name:"Aiden & Sophie Clarke",phone:"0433 112 889",email:"aidensophieclarke@gmail.com",purchase_address:"15 Hartsmere Drive",suburb:"Berwick",purchase_date:"2026-05-02",purchase_price:845000,deposit:169000,property_type:"House",beds:3,baths:2,land:520,status:"owner-occupier",notes:"Aiden a senior project engineer, Sophie a speech pathologist. Bought 15 Hartsmere Drive after attending three open homes. Very decisive buyers.",last_contact_date:"2026-06-01"},
  {id:7025,agent_name:"Manpreet Singh",name:"Sri & Priya De Ros",phone:"0417 445 223",email:"srideross@gmail.com",purchase_address:"40 Jack William Way",suburb:"Berwick",purchase_date:"2026-05-25",purchase_price:805000,deposit:161000,property_type:"House",beds:3,baths:2,land:480,status:"owner-occupier",notes:"Sri a systems analyst, Priya a GP. Bought 40 Jack William Way as their forever home after years of saving. Love the community on Jack William Way.",last_contact_date:"2026-06-24"},
]

// ── Upsert all rows ──────────────────────────────────────────────────────────
async function main() {
  console.log('🚀 PropOS → Supabase Migration')
  console.log(`   Rows to upsert: ${ALL_BUYERS.length} (88 Cameron + 25 Manpreet)`)
  console.log(`   Project: pzdcwulzteofvatjrtlh\n`)

  // Test connection
  const { error: connErr } = await supabase.from('past_buyers').select('id').limit(1)
  if (connErr?.code === 'PGRST205' || (connErr && connErr.message?.includes('schema cache'))) {
    console.error('❌ Table does not exist yet.')
    console.log('\n📋 STEP 1: Run this SQL in Supabase Dashboard → SQL Editor:')
    console.log('   https://supabase.com/dashboard/project/pzdcwulzteofvatjrtlh/sql/new\n')
    console.log('   Paste the contents of: supabase/migrations/20260606_create_past_buyers.sql')
    console.log('\n   Then re-run: node scripts/supabase-migrate.mjs')
    process.exit(1)
  }

  if (connErr) {
    console.error('❌ Connection error:', connErr.message)
    process.exit(1)
  }

  console.log('✅ Connected to Supabase\n')

  // Upsert in batches of 25
  const BATCH = 25
  let totalUpserted = 0
  let errors = 0

  for (let i = 0; i < ALL_BUYERS.length; i += BATCH) {
    const batch = ALL_BUYERS.slice(i, i + BATCH)
    const { data, error } = await supabase
      .from('past_buyers')
      .upsert(batch, { onConflict: 'id', ignoreDuplicates: false })
      .select('id')

    if (error) {
      console.error(`❌ Batch ${Math.floor(i/BATCH)+1} error:`, error.message)
      errors++
    } else {
      totalUpserted += batch.length
      const agentGroups = [...new Set(batch.map(b => b.agent_name))]
      console.log(`✅ Batch ${Math.floor(i/BATCH)+1}: ${batch.length} rows (${agentGroups.join(', ')})`)
    }
  }

  console.log(`\n📊 Results:`)
  console.log(`   ✅ Upserted: ${totalUpserted} rows`)
  if (errors > 0) console.log(`   ❌ Failed batches: ${errors}`)

  // Verify
  const { data: cam } = await supabase.from('past_buyers').select('id').eq('agent_name','Cameron Knoll')
  const { data: man } = await supabase.from('past_buyers').select('id').eq('agent_name','Manpreet Singh')
  console.log(`\n🔍 Verification:`)
  console.log(`   Cameron Knoll: ${cam?.length ?? 0} rows in Supabase`)
  console.log(`   Manpreet Singh: ${man?.length ?? 0} rows in Supabase`)
  console.log(`   Total: ${(cam?.length ?? 0) + (man?.length ?? 0)} rows`)

  if ((cam?.length ?? 0) === 88 && (man?.length ?? 0) === 25) {
    console.log('\n🎉 100% migration confirmed — 88 Cameron + 25 Manpreet = 113 total ✅')
    console.log('\n📝 Next steps:')
    console.log('   1. Set VITE_SUPABASE_URL in Railway env (your Supabase project URL)')
    console.log('   2. Set VITE_SUPABASE_ANON_KEY in Railway env (anon/publishable key)')
    console.log('   3. Set SUPABASE_SERVICE_KEY in Railway env (service role key)')
    console.log('   4. Redeploy: railway up --detach')
  } else {
    console.log('\n⚠️  Row counts don\'t match expected values — check errors above')
  }
}

main().catch(console.error)
